# Generated by Django 5.0.7 on 2025-10-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nft_data', '0013_nft_active_auction_nft_asking_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for this category', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display categories (lower numbers first)')),
            ],
            options={
                'verbose_name_plural': 'Achievement Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier (e.g., 'FIRST_BID', 'TOP_TRADER')", max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', help_text='Rarity level of this achievement', max_length=20)),
                ('points', models.PositiveIntegerField(default=10, help_text='Points awarded for earning this achievement')),
                ('icon_url', models.URLField(blank=True, help_text='URL to the badge icon', max_length=500, null=True)),
                ('icon_image', models.ImageField(blank=True, help_text='Uploaded icon image', null=True, upload_to='achievement_icons/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this achievement can be earned')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden achievements are not shown until earned')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order within category (lower numbers first)')),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Optional: Store criteria data for automatic awarding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='profiles.achievementcategory')),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Public display name (optional, defaults to username)', max_length=50)),
                ('bio', models.TextField(blank=True, help_text='A short description about the user (max 160 chars)', max_length=160)),
                ('avatar_type', models.CharField(choices=[('upload', 'Uploaded Image'), ('nft', 'NFT Profile Picture'), ('url', 'External URL')], default='upload', help_text='Type of avatar being used', max_length=20)),
                ('avatar_image', models.ImageField(blank=True, help_text='Uploaded avatar image', null=True, upload_to='avatars/')),
                ('avatar_url', models.URLField(blank=True, help_text='External URL for avatar (if not uploading)', max_length=500, null=True)),
                ('avatar_nft_mint', models.CharField(blank=True, help_text='NFT mint address to use as profile picture', max_length=44, null=True)),
                ('social_x', models.CharField(blank=True, help_text='X (Twitter) handle (without @)', max_length=50)),
                ('social_discord', models.CharField(blank=True, help_text='Discord username (e.g., username#1234)', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Link to personal website or portfolio', max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='Allow others to view this profile?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='profiles.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('NFT', 'NFT'), ('COLLECTION', 'Collection')], help_text='Type of item being watched', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about why watching this item', max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='nft_data.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['is_active', 'is_hidden'], name='profiles_ac_is_acti_277314_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category', 'display_order'], name='profiles_ac_categor_d76d16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['user', 'item_type'], name='profiles_wa_user_id_950bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['user', 'added_at'], name='profiles_wa_user_id_877061_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'collection'), ('user', 'nft')},
        ),
    ]
