# Generated by Django 5.0.7 on 2025-11-05 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_delete_adminnotification'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.BigIntegerField(help_text='Unique quest ID (u64) used on-chain', unique=True)),
                ('title', models.CharField(help_text='Display name for the quest', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of what users need to do')),
                ('action_type', models.CharField(choices=[('buy', 'Buy NFTs'), ('bid', 'Place Bids'), ('list', 'List NFTs')], help_text='Type of action required', max_length=10)),
                ('target_count', models.PositiveIntegerField(help_text='Number of actions required to complete (u32)', validators=[django.core.validators.MinValueValidator(1)])),
                ('reward_lamports', models.BigIntegerField(help_text='Reward in lamports (1 SOL = 1,000,000,000 lamports)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Deployment'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='draft', help_text='Current status of the quest', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the quest is active on-chain')),
                ('icon', models.CharField(blank=True, default='🎯', help_text='Emoji or icon for the quest', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('start_date', models.DateTimeField(blank=True, help_text='When the quest becomes available', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the quest expires', null=True)),
                ('on_chain_address', models.CharField(blank=True, help_text='Solana address of the deployed quest PDA', max_length=44)),
                ('deployment_signature', models.CharField(blank=True, help_text='Transaction signature of quest creation', max_length=88)),
                ('deployed_at', models.DateTimeField(blank=True, help_text='When the quest was deployed on-chain', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time on-chain status was synced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_created', to='admin_panel.adminuser')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_lamports', models.BigIntegerField(help_text='Amount claimed (snapshot at claim time)')),
                ('transaction_signature', models.CharField(help_text='Solana transaction signature of the claim', max_length=88)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='profiles.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestUserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfts_bought', models.PositiveIntegerField(default=0)),
                ('bids_placed', models.PositiveIntegerField(default=0)),
                ('nfts_listed', models.PositiveIntegerField(default=0)),
                ('on_chain_address', models.CharField(blank=True, help_text="User's quest account PDA on Solana", max_length=44)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last time progress was synced from on-chain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quest user progress',
            },
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['quest_id'], name='profiles_qu_quest_i_a42dba_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['status', 'is_active'], name='profiles_qu_status_545637_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['action_type'], name='profiles_qu_action__dce2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='questclaim',
            index=models.Index(fields=['user', '-claimed_at'], name='profiles_qu_user_id_82c952_idx'),
        ),
        migrations.AddIndex(
            model_name='questclaim',
            index=models.Index(fields=['quest', '-claimed_at'], name='profiles_qu_quest_i_1a4711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questclaim',
            unique_together={('user', 'quest')},
        ),
        migrations.AddIndex(
            model_name='questuserprogress',
            index=models.Index(fields=['user'], name='profiles_qu_user_id_a1ff9b_idx'),
        ),
    ]
