# Generated by Django 5.0.7 on 2025-09-28 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0013_remove_advancedcrossmarketplaceanalysis_collection_and_more'),
        ('nft_data', '0010_remove_collectionsweepevent_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProminence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=44, unique=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('transaction_volume', models.FloatField(default=0.0)),
                ('collections_count', models.IntegerField(default=0)),
                ('prominence_score', models.FloatField(db_index=True, default=0.0, help_text="Score (0-100) indicating wallet's market influence.")),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-prominence_score'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedCollectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_price', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('listed_count', models.IntegerField(default=0)),
                ('total_supply', models.IntegerField(default=0)),
                ('number_of_holders', models.IntegerField(default=0)),
                ('vitality_score', models.FloatField(default=0.0, help_text="TraitKeeper's proprietary collection health score.")),
                ('holder_quality_score', models.FloatField(default=0.0)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('market_influence_score', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('market_cap', models.DecimalField(decimal_places=9, default=0, max_digits=25)),
                ('price_change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_7d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('percent_listed', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('velocity_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('market_efficiency_score', models.FloatField(default=0.0)),
                ('holder_confidence_index', models.FloatField(default=0.0)),
                ('liquidity_health_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_attribution', models.JSONField(default=dict, help_text='Details which source was used for each aggregated field.')),
                ('collection', models.OneToOneField(help_text='The collection these analytics apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_stats', to='nft_data.nftcollection')),
            ],
        ),
        migrations.CreateModel(
            name='TopTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.nftcollection')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traitvalue')),
            ],
            options={
                'ordering': ['-combined_score'],
            },
        ),
        migrations.CreateModel(
            name='TrendingTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.nftcollection')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traitvalue')),
            ],
            options={
                'ordering': ['-trend_score'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSweepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_address', models.CharField(db_index=True, help_text='The primary wallet address leading the sweep.', max_length=44)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('num_items', models.IntegerField(help_text='Number of NFTs purchased during the sweep.')),
                ('total_volume', models.FloatField(help_text='Total SOL spent during the sweep.')),
                ('significance_score', models.FloatField(default=0.0, help_text='A score (0-100) indicating the market impact of the sweep.')),
                ('nft_mints', models.JSONField(default=list, help_text='A list of mint addresses of the NFTs that were swept.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_events', to='nft_data.nftcollection')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['collection', '-significance_score'], name='analytics_c_collect_2d02e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='HighProfileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_profile_score', models.FloatField(default=0.0, help_text='A score indicating the significance of this transfer.')),
                ('value_factor', models.FloatField(default=0.0)),
                ('wallet_factor', models.FloatField(default=0.0)),
                ('timing_factor', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_profile_transfers', to='nft_data.nftcollection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_profile_transfers', to='indexer.nftevent')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_profile_transfers', to='nft_data.nft')),
            ],
            options={
                'ordering': ['-high_profile_score'],
                'indexes': [models.Index(fields=['collection', '-high_profile_score'], name='analytics_h_collect_6e0148_idx')],
            },
        ),
        migrations.CreateModel(
            name='TraitPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_score', models.FloatField(default=0.0, help_text='The rarity percentage of this trait.')),
                ('avg_sale_price', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('premium_score', models.FloatField(default=0.0, help_text='The calculated price premium this trait commands over the floor.')),
                ('velocity_score', models.FloatField(default=0.0, help_text='A measure of how quickly NFTs with this trait are sold.')),
                ('momentum_score', models.FloatField(default=0.0, help_text='The recent price trend for this trait.')),
                ('performance_score', models.FloatField(db_index=True, default=0.0, help_text='The final combined performance score for this trait.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_performance_scores', to='nft_data.nftcollection')),
                ('trait_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='nft_data.traittype')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='nft_data.traitvalue')),
            ],
            options={
                'ordering': ['-performance_score'],
                'indexes': [models.Index(fields=['collection', '-performance_score'], name='analytics_t_collect_3abc2e_idx'), models.Index(fields=['trait_value', '-performance_score'], name='analytics_t_trait_v_85ae45_idx')],
                'unique_together': {('collection', 'trait_value')},
            },
        ),
        migrations.CreateModel(
            name='WalletBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=44, unique=True)),
                ('behavior_type', models.CharField(choices=[('whale', 'Whale'), ('scalper', 'Scalper'), ('holder', 'Long-term Holder'), ('flipper', 'Quick Flipper'), ('collector', 'Collector'), ('arbitrageur', 'Arbitrageur'), ('market_maker', 'Market Maker'), ('institutional', 'Institutional'), ('bot', 'Bot/Automated'), ('casual', 'Casual Trader')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in behavior classification (0-1)')),
                ('avg_hold_time_hours', models.FloatField(default=0.0)),
                ('trade_frequency_per_day', models.FloatField(default=0.0)),
                ('avg_profit_margin', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('risk_tolerance', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('max_single_purchase', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('diversification_score', models.FloatField(default=0.0, help_text='How diversified their portfolio is (0-1)')),
                ('influence_score', models.FloatField(default=0.0, help_text='How much this wallet influences market movements (0-1)')),
                ('trendsetting_ability', models.FloatField(default=0.0, help_text="How often this wallet's actions predict trends (0-1)")),
                ('copy_trader_count', models.IntegerField(default=0, help_text="Estimated number of wallets that copy this wallet's trades")),
                ('network_centrality', models.FloatField(default=0.0, help_text='Position in the trading network (0-1)')),
                ('most_active_hours', models.JSONField(default=list, help_text='Hours of day when most active (0-23)')),
                ('seasonal_patterns', models.JSONField(default=dict, help_text='Seasonal trading patterns and preferences')),
                ('collection_loyalty_score', models.FloatField(default=0.0, help_text='How loyal to specific collections (0-1)')),
                ('fomo_susceptibility', models.FloatField(default=0.0, help_text='How susceptible to FOMO buying (0-1)')),
                ('contrarian_indicator', models.FloatField(default=0.0, help_text='How often they trade against the trend (0-1)')),
                ('market_timing_ability', models.FloatField(default=0.0, help_text='Ability to time market entries/exits (0-1)')),
                ('behavior_features', models.JSONField(default=dict, help_text='ML: Feature vector for behavior classification')),
                ('clustering_assignment', models.IntegerField(blank=True, help_text='ML: Cluster assignment from unsupervised learning', null=True)),
                ('first_seen', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=9, default=0, max_digits=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_collections', models.ManyToManyField(blank=True, related_name='preferred_by_wallets', to='nft_data.nftcollection')),
            ],
            options={
                'ordering': ['-influence_score'],
                'indexes': [models.Index(fields=['behavior_type', 'influence_score'], name='analytics_w_behavio_429fe7_idx'), models.Index(fields=['confidence_score', 'updated_at'], name='analytics_w_confide_a5c36a_idx'), models.Index(fields=['risk_tolerance', 'total_volume'], name='analytics_w_risk_to_ace36c_idx'), models.Index(fields=['clustering_assignment', 'behavior_type'], name='analytics_w_cluster_bc1d6f_idx')],
            },
        ),
    ]
