# Generated by Django 5.1.10 on 2025-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitperformancescore',
            name='sales_count_24h',
            field=models.IntegerField(default=0, help_text='Number of sales for NFTs with this trait in last 24 hours'),
        ),
        migrations.AddField(
            model_name='traitperformancescore',
            name='sales_count_7d',
            field=models.IntegerField(default=0, help_text='Number of sales for NFTs with this trait in last 7 days'),
        ),
        migrations.AddField(
            model_name='traitperformancescore',
            name='volume_24h',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Total SOL volume for NFTs with this trait in last 24 hours', max_digits=20),
        ),
        migrations.AddField(
            model_name='traitperformancescore',
            name='volume_7d',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Total SOL volume for NFTs with this trait in last 7 days', max_digits=20),
        ),
    ]
