# Generated by Django 5.1.10 on 2025-12-29 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_traitperformancescore_sales_count_24h_and_more'),
        ('nft_data', '0014_alter_pendingcollection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, help_text='Solana wallet address to blacklist', max_length=44, unique=True)),
                ('reason', models.CharField(choices=[('bot_listing', 'Bot Listing Activity'), ('wash_trading', 'Wash Trading'), ('price_manipulation', 'Price Manipulation'), ('spam_transactions', 'Spam Transactions'), ('sybil_attack', 'Sybil Attack'), ('coordinated_pumping', 'Coordinated Pumping'), ('fake_volume', 'Fake Volume Generation'), ('manual_review', 'Manual Review'), ('other', 'Other Suspicious Activity')], help_text='Primary reason for blacklisting', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active (Blacklisted)'), ('monitoring', 'Under Monitoring'), ('cleared', 'Cleared (No Longer Blacklisted)')], default='active', help_text='Current blacklist status', max_length=20)),
                ('detection_method', models.CharField(choices=[('automatic', 'Automatic Detection'), ('manual', 'Manual Review'), ('community_report', 'Community Reported'), ('third_party', 'Third-Party Intelligence')], default='automatic', help_text='How this wallet was identified', max_length=50)),
                ('suspicious_patterns', models.JSONField(default=dict, help_text='Detected suspicious patterns and their scores')),
                ('total_transactions_analyzed', models.IntegerField(default=0, help_text='Total transactions analyzed for this wallet')),
                ('suspicious_transaction_count', models.IntegerField(default=0, help_text='Number of transactions flagged as suspicious')),
                ('manipulation_score', models.FloatField(default=0.0, help_text='Overall manipulation score (0-100, higher = more suspicious)')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from manual review or automated analysis')),
                ('reviewed_by', models.CharField(blank=True, help_text='Username or system that reviewed this wallet', max_length=100)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_activity_detected', models.DateTimeField(auto_now=True, help_text='Last time suspicious activity was detected')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, help_text='When this wallet was added to blacklist')),
                ('cleared_at', models.DateTimeField(blank=True, help_text='When blacklist was removed (if applicable)', null=True)),
                ('auto_clear_after_days', models.IntegerField(blank=True, help_text='Automatically clear from blacklist after N days of no suspicious activity', null=True)),
                ('affected_collections', models.ManyToManyField(blank=True, help_text='Collections where this wallet showed suspicious activity', related_name='blacklisted_wallets', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Blacklisted Wallet',
                'verbose_name_plural': 'Blacklisted Wallets',
                'ordering': ['-manipulation_score', '-first_detected'],
            },
        ),
        migrations.CreateModel(
            name='WalletSuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, help_text='Wallet address showing suspicious activity', max_length=44)),
                ('activity_type', models.CharField(choices=[('rapid_listing_creation', 'Rapid Listing Creation/Cancellation'), ('circular_trading', 'Circular Trading Pattern'), ('price_spiking', 'Artificial Price Spiking'), ('volume_inflation', 'Volume Inflation'), ('collection_sweep_bot', 'Automated Collection Sweeping'), ('listing_manipulation', 'Listing Count Manipulation'), ('bid_spoofing', 'Bid Spoofing'), ('front_running', 'Front Running')], help_text='Type of suspicious activity detected', max_length=40)),
                ('severity_score', models.FloatField(default=0.0, help_text='Severity of this activity (0-100)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in detection (0-1)')),
                ('transaction_signatures', models.JSONField(default=list, help_text='List of transaction signatures involved')),
                ('evidence_data', models.JSONField(default=dict, help_text='Detailed evidence and metrics')),
                ('pattern_description', models.TextField(help_text='Description of the suspicious pattern detected')),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('reviewed', models.BooleanField(default=False, help_text='Whether this activity has been reviewed')),
                ('false_positive', models.BooleanField(default=False, help_text='Marked as false positive after review')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('blacklisted_wallet', models.ForeignKey(blank=True, help_text='Link to blacklist record if wallet is blacklisted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='analytics.blacklistedwallet')),
                ('collection', models.ForeignKey(help_text='Collection where activity occurred', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_suspicious_activities', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Suspicious Wallet Activity',
                'verbose_name_plural': 'Suspicious Wallet Activities',
                'ordering': ['-severity_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Scam Collection'), ('rug_pull', 'Rug Pull'), ('wash_trading_collection', 'Collection-Wide Wash Trading'), ('bot_network', 'Bot Network Operation'), ('copyright_violation', 'Copyright Violation'), ('spam_collection', 'Spam/Low Quality'), ('malicious_contract', 'Malicious Smart Contract'), ('impersonation', 'Impersonating Legitimate Project'), ('manual_review', 'Manual Review Required'), ('other', 'Other')], help_text='Primary reason for blacklisting', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active (Blacklisted)'), ('monitoring', 'Under Monitoring'), ('cleared', 'Cleared')], default='active', help_text='Current blacklist status', max_length=20)),
                ('detection_method', models.CharField(choices=[('automatic', 'Automatic Detection'), ('manual', 'Manual Review'), ('community_report', 'Community Reported'), ('third_party', 'Third-Party Intelligence')], default='manual', help_text='How this collection was flagged', max_length=50)),
                ('evidence_data', models.JSONField(default=dict, help_text='Evidence and suspicious patterns detected')),
                ('risk_score', models.FloatField(default=0.0, help_text='Overall risk score (0-100, higher = more suspicious)')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from review')),
                ('reviewed_by', models.CharField(blank=True, help_text='Who reviewed this', max_length=100)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('hide_from_listings', models.BooleanField(default=True, help_text='Hide from public collection listings')),
                ('show_warning', models.BooleanField(default=True, help_text='Show warning banner if accessed directly')),
                ('collection', models.OneToOneField(help_text='Collection to blacklist', on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_status', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Blacklisted Collection',
                'verbose_name_plural': 'Blacklisted Collections',
                'ordering': ['-risk_score', '-first_detected'],
                'indexes': [models.Index(fields=['status', 'reason'], name='analytics_b_status_c99105_idx'), models.Index(fields=['risk_score', 'status'], name='analytics_b_risk_sc_712fe6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='blacklistedwallet',
            index=models.Index(fields=['wallet_address', 'status'], name='analytics_b_wallet__537f77_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedwallet',
            index=models.Index(fields=['status', 'reason'], name='analytics_b_status_57ef09_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedwallet',
            index=models.Index(fields=['manipulation_score', 'status'], name='analytics_b_manipul_f7a5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedwallet',
            index=models.Index(fields=['first_detected', 'status'], name='analytics_b_first_d_76fbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='walletsuspiciousactivity',
            index=models.Index(fields=['wallet_address', 'activity_type', 'detected_at'], name='analytics_w_wallet__139630_idx'),
        ),
        migrations.AddIndex(
            model_name='walletsuspiciousactivity',
            index=models.Index(fields=['collection', 'severity_score'], name='analytics_w_collect_230e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='walletsuspiciousactivity',
            index=models.Index(fields=['reviewed', 'false_positive'], name='analytics_w_reviewe_678e52_idx'),
        ),
    ]
