# Generated by Django 5.0.7 on 2025-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminnotification_details_adminnotification_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('server_load', 'High Server Load'), ('failed_login', 'Failed Login Attempt'), ('collection_populated', 'Collections Populated'), ('collection_refreshed', 'Collections Refreshed'), ('collection_submitted', 'Collection Submitted'), ('collection_action', 'Collection Action')], max_length=50),
        ),
    ]
