# Generated by Django 5.0.7 on 2025-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_adminnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('server_load', 'High Server Load'), ('failed_login', 'Failed Login Attempt'), ('collection_populated', 'Collections Populated'), ('collection_refreshed', 'Collections Refreshed'), ('collection_submitted', 'Collection Submitted'), ('collection_action', 'Collection Action'), ('system_alert', 'System Alert'), ('magic_eden_issue', 'Magic Eden Issue'), ('data_anomaly', 'Data Anomaly'), ('performance_issue', 'Performance Issue'), ('collection_issue', 'Collection Issue')], max_length=50),
        ),
    ]
