# Generated by Django 5.1.10 on 2025-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_delete_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provider name (e.g., 'magic_eden', 'tensor')", max_length=50, unique=True)),
                ('api_key', models.CharField(help_text='API key for the marketplace provider', max_length=200)),
                ('base_url', models.URLField(blank=True, help_text='Optional custom base URL (uses provider default if empty)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active and should be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Provider Setting',
                'verbose_name_plural': 'Marketplace Provider Settings',
            },
        ),
    ]
