# Generated by Django 5.0.7 on 2025-09-28 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0013_remove_advancedcrossmarketplaceanalysis_collection_and_more'),
        ('nft_data', '0010_remove_collectionsweepevent_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('auction_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('creator', models.CharField(db_index=True, help_text='Wallet address of the auction creator.', max_length=44)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(db_index=True, help_text='When the auction is scheduled to end.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('starting_price', models.DecimalField(decimal_places=9, help_text='The minimum opening bid in SOL.', max_digits=20)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=9, help_text='The current highest bid in SOL.', max_digits=20, null=True)),
                ('current_bidder', models.CharField(blank=True, db_index=True, max_length=44, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=9, help_text='The winning bid amount in SOL.', max_digits=20, null=True)),
                ('winner', models.CharField(blank=True, db_index=True, max_length=44, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'Auction Event',
                'verbose_name_plural': 'Auction Events',
                'ordering': ['-end_time'],
                'indexes': [models.Index(fields=['status', 'end_time'], name='marketplace_status_ff345d_idx'), models.Index(fields=['collection', 'status'], name='marketplace_collect_a329c0_idx'), models.Index(fields=['nft', 'status'], name='marketplace_nft_id_0f7821_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('tx_signature', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SALE', 'Direct Sale'), ('AUCTION', 'Auction Sale')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=9, help_text='The fee amount collected in SOL.', max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fees', to='indexer.nftevent')),
            ],
            options={
                'verbose_name': 'Platform Fee',
                'verbose_name_plural': 'Platform Fees',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='marketplace_event_t_6751cb_idx')],
            },
        ),
    ]
