# Generated by Django 5.0.7 on 2025-10-15 03:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0015_unknowndiscriminator'),
        ('marketplace', '0001_initial'),
        ('nft_data', '0010_remove_collectionsweepevent_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumBidThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_minimum_sol', models.DecimalField(blank=True, decimal_places=9, help_text='Hard minimum price in SOL (e.g., 0.5 SOL)', max_digits=20, null=True)),
                ('vitality_percentage_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Max % below vitality allowed (e.g., -15.00 means -15%)', max_digits=5, null=True)),
                ('threshold_type', models.CharField(choices=[('ABSOLUTE', 'Absolute SOL Minimum'), ('VITALITY_BASED', 'Vitality Percentage-Based'), ('BOTH', 'Use Whichever is Higher')], default='VITALITY_BASED', help_text='Which threshold rule to enforce', max_length=20)),
                ('set_by', models.CharField(choices=[('SYSTEM', 'System Default'), ('OWNER', 'NFT Owner'), ('ADMIN', 'Platform Admin')], default='SYSTEM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Can be disabled without deleting')),
                ('collection', models.ForeignKey(blank=True, help_text='If set, this threshold applies to the entire collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_thresholds', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(blank=True, help_text='If set, this threshold applies to this specific NFT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_threshold', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'Minimum Bid Threshold',
                'verbose_name_plural': 'Minimum Bid Thresholds',
            },
        ),
        migrations.CreateModel(
            name='NFTVitality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitality_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Final weighted vitality score (0-100)', max_digits=5)),
                ('market_momentum', models.FloatField(default=0.5, help_text='Price/interest momentum over 60 days (0-1)')),
                ('trait_performance', models.FloatField(default=0.5, help_text="Avg performance of this NFT's traits (0-1)")),
                ('collection_health', models.FloatField(default=0.5, help_text="Parent collection's market health (0-1)")),
                ('collection_utility', models.FloatField(default=0.5, help_text="Collection's utility/use-case value (0-1)")),
                ('rarity_score', models.FloatField(default=0.5, help_text='Trait combination rarity (0-1)')),
                ('holder_quality', models.FloatField(default=0.5, help_text="Current holder's wallet quality (0-1)")),
                ('sentiment_score', models.FloatField(default=0.5, help_text='Community sentiment (0-1) - TODO: Not yet implemented')),
                ('market_influence', models.FloatField(default=0.5, help_text='Market influence score (0-1)')),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=9, help_text='Suggested SOL price based on vitality - NOT YET IMPLEMENTED', max_digits=20, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='When this vitality score was last updated')),
                ('calculation_source', models.CharField(default='system', help_text='What triggered this calculation (system, manual, event)', max_length=50)),
                ('has_sufficient_data', models.BooleanField(default=False, help_text='True if collection has at least 1 transaction for calculation')),
                ('nft', models.OneToOneField(help_text='The NFT this vitality score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vitality', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'NFT Vitality',
                'verbose_name_plural': 'NFT Vitalities',
            },
        ),
        migrations.CreateModel(
            name='NFTVitalityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitality_score', models.DecimalField(decimal_places=2, help_text='Vitality score at this timestamp', max_digits=5)),
                ('market_momentum', models.FloatField()),
                ('trait_performance', models.FloatField()),
                ('collection_health', models.FloatField()),
                ('collection_utility', models.FloatField()),
                ('rarity_score', models.FloatField()),
                ('holder_quality', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('market_influence', models.FloatField()),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this snapshot was created')),
                ('nft', models.ForeignKey(help_text='The NFT this historical record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vitality_history', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'NFT Vitality History',
                'verbose_name_plural': 'NFT Vitality Histories',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalityPriceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_sale_price', models.DecimalField(decimal_places=9, help_text='Actual SOL price the NFT sold for', max_digits=20)),
                ('marketplace', models.CharField(help_text='Where the sale occurred (magic_eden, tensor, traitkeeper, etc.)', max_length=50)),
                ('vitality_at_sale', models.DecimalField(decimal_places=2, help_text='Vitality score when the NFT was sold', max_digits=5)),
                ('suggested_price_at_sale', models.DecimalField(blank=True, decimal_places=9, help_text='What vitality suggested the price should be', max_digits=20, null=True)),
                ('price_difference_sol', models.DecimalField(decimal_places=9, help_text='Actual - Suggested (positive = sold above vitality)', max_digits=20)),
                ('price_difference_percent', models.DecimalField(decimal_places=4, help_text='(Actual - Suggested) / Suggested * 100', max_digits=10)),
                ('collection_floor_at_sale', models.DecimalField(decimal_places=9, help_text='Collection floor price at time of sale', max_digits=20)),
                ('vs_floor_percent', models.DecimalField(decimal_places=4, help_text='How the actual price compared to floor', max_digits=10)),
                ('sale_timestamp', models.DateTimeField(help_text='When the sale occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitality_comparisons', to='nft_data.nft')),
                ('sale_event', models.OneToOneField(help_text='The sale event being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='vitality_comparison', to='indexer.nftevent')),
            ],
            options={
                'verbose_name': 'Vitality Price Comparison',
                'verbose_name_plural': 'Vitality Price Comparisons',
                'ordering': ['-sale_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CollectionVitality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitality_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Collection-level vitality score (0-100)', max_digits=5)),
                ('market_momentum', models.FloatField(default=0.5, help_text="Collection's price/volume momentum over 60 days (0-1)")),
                ('avg_trait_performance', models.FloatField(default=0.5, help_text='Average trait performance across collection (0-1)')),
                ('collection_health', models.FloatField(default=0.5, help_text='Overall market health (0-1)')),
                ('collection_utility', models.FloatField(default=0.5, help_text="Collection's utility/use-case value (0-1)")),
                ('avg_rarity_score', models.FloatField(default=0.5, help_text='Average rarity across collection (0-1)')),
                ('holder_quality_avg', models.FloatField(default=0.5, help_text='Average holder quality (0-1)')),
                ('sentiment_score', models.FloatField(default=0.5, help_text='Collection sentiment (0-1) - TODO: Not yet implemented')),
                ('market_influence', models.FloatField(default=0.5, help_text="Collection's market influence (0-1)")),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('has_sufficient_data', models.BooleanField(default=False, help_text='True if collection has at least 1 transaction')),
                ('collection', models.OneToOneField(help_text='The collection this vitality score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vitality', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Collection Vitality',
                'verbose_name_plural': 'Collection Vitalities',
                'indexes': [models.Index(fields=['vitality_score', '-last_calculated'], name='marketplace_vitalit_210bc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionVitalityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitality_score', models.DecimalField(decimal_places=2, help_text='Collection vitality at this timestamp', max_digits=5)),
                ('market_momentum', models.FloatField()),
                ('avg_trait_performance', models.FloatField()),
                ('collection_health', models.FloatField()),
                ('collection_utility', models.FloatField()),
                ('avg_rarity_score', models.FloatField()),
                ('holder_quality_avg', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('market_influence', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collection', models.ForeignKey(help_text='The collection this historical record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vitality_history', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Collection Vitality History',
                'verbose_name_plural': 'Collection Vitality Histories',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['collection', '-calculated_at'], name='marketplace_collect_be8a91_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='minimumbidthreshold',
            constraint=models.CheckConstraint(check=models.Q(('collection__isnull', False), ('nft__isnull', False), _connector='OR'), name='threshold_must_have_collection_or_nft'),
        ),
        migrations.AddConstraint(
            model_name='minimumbidthreshold',
            constraint=models.CheckConstraint(check=models.Q(('collection__isnull', False), ('nft__isnull', False), _negated=True), name='threshold_cannot_have_both_collection_and_nft'),
        ),
        migrations.AddIndex(
            model_name='nftvitality',
            index=models.Index(fields=['vitality_score', '-last_calculated'], name='marketplace_vitalit_2d9179_idx'),
        ),
        migrations.AddIndex(
            model_name='nftvitality',
            index=models.Index(fields=['has_sufficient_data', 'vitality_score'], name='marketplace_has_suf_09fa62_idx'),
        ),
        migrations.AddIndex(
            model_name='nftvitalityhistory',
            index=models.Index(fields=['nft', '-calculated_at'], name='marketplace_nft_id_055fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='nftvitalityhistory',
            index=models.Index(fields=['calculated_at', 'vitality_score'], name='marketplace_calcula_5ff00e_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalitypricecomparison',
            index=models.Index(fields=['nft', '-sale_timestamp'], name='marketplace_nft_id_b8bdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalitypricecomparison',
            index=models.Index(fields=['marketplace', '-sale_timestamp'], name='marketplace_marketp_a9981e_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalitypricecomparison',
            index=models.Index(fields=['-price_difference_percent'], name='marketplace_price_d_6c0609_idx'),
        ),
    ]
