# Generated by Django 5.0.7 on 2025-10-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0015_unknowndiscriminator'),
        ('marketplace', '0003_collectionvitality_updated_at_and_more'),
        ('nft_data', '0012_nft_buy_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BID_ACCEPTED', 'Private Bid Accepted'), ('DIRECT_SALE', 'Direct Buy Now Purchase'), ('AUCTION_SALE', 'Auction Sale'), ('COUNTER_OFFER_ACCEPTED', 'Counter Offer Accepted')], help_text='Type of marketplace transaction', max_length=30)),
                ('was_encrypted', models.BooleanField(default=False, help_text='Was this transaction encrypted (private bid/auction)?')),
                ('reveal_timestamp', models.DateTimeField(blank=True, help_text='When the encrypted bid/price was revealed', null=True)),
                ('nft_vitality_at_sale', models.DecimalField(blank=True, decimal_places=2, help_text='NFT vitality score when sold', max_digits=5, null=True)),
                ('suggested_price_at_sale', models.DecimalField(blank=True, decimal_places=9, help_text='Vitality-suggested price at time of sale (SOL)', max_digits=20, null=True)),
                ('vs_vitality_suggested', models.DecimalField(blank=True, decimal_places=2, help_text='Price vs vitality suggestion multiplier (e.g., 1.25 = 25% above)', max_digits=10, null=True)),
                ('vs_collection_floor', models.DecimalField(blank=True, decimal_places=2, help_text='Price vs collection floor multiplier', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft_event', models.OneToOneField(help_text='The NFTEvent this transaction is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_transaction', to='indexer.nftevent')),
            ],
            options={
                'verbose_name': 'Marketplace Transaction',
                'verbose_name_plural': 'Marketplace Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', '-created_at'], name='marketplace_transac_f02f46_idx'), models.Index(fields=['was_encrypted', '-created_at'], name='marketplace_was_enc_933798_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivateBid',
            fields=[
                ('bid_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('bidder', models.CharField(db_index=True, help_text='Wallet address of the bidder', max_length=44)),
                ('owner_at_creation', models.CharField(db_index=True, help_text='NFT owner when bid was placed (for tracking ownership changes)', max_length=44)),
                ('encrypted_state_account', models.CharField(help_text='Reference to on-chain encrypted state (Arcium account address)', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted (Sale Executed)'), ('REJECTED', 'Rejected by Owner'), ('CANCELLED', 'Cancelled by Bidder'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this bid automatically expires')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the bid was accepted/rejected/cancelled', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(help_text='The collection this NFT belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='private_bids', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(help_text='The NFT this bid is for', on_delete=django.db.models.deletion.CASCADE, related_name='private_bids', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'Private Bid',
                'verbose_name_plural': 'Private Bids',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nft', 'status', '-created_at'], name='marketplace_nft_id_e50160_idx'), models.Index(fields=['bidder', 'status'], name='marketplace_bidder_f04bf0_idx'), models.Index(fields=['status', 'expires_at'], name='marketplace_status_8d29e6_idx'), models.Index(fields=['collection', 'status'], name='marketplace_collect_427b44_idx')],
            },
        ),
    ]
