# Generated by Django 5.0.7 on 2025-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_marketplacetransaction_privatebid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionevent',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
    ]
