# Generated by Django 5.0.7 on 2025-10-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auctionevent_bid_count'),
        ('nft_data', '0013_nft_active_auction_nft_asking_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('bidder', models.CharField(db_index=True, help_text='Wallet address of the bidder', max_length=44)),
                ('amount', models.DecimalField(decimal_places=9, help_text='Bid amount in SOL', max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('OUTBID', 'Outbid')], db_index=True, default='ACTIVE', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this bid expires', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(blank=True, help_text='Related auction if this is an auction bid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.auctionevent')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(help_text='The NFT this bid is for', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-placed_at'],
                'indexes': [models.Index(fields=['bidder', 'status'], name='marketplace_bidder_aaa301_idx'), models.Index(fields=['nft', 'status'], name='marketplace_nft_id_9b5a03_idx'), models.Index(fields=['auction', 'status'], name='marketplace_auction_1547d2_idx'), models.Index(fields=['status', '-placed_at'], name='marketplace_status_2bf780_idx')],
            },
        ),
        migrations.CreateModel(
            name='NFTListing',
            fields=[
                ('listing_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('seller', models.CharField(db_index=True, help_text='Wallet address of the seller', max_length=44)),
                ('listing_type', models.CharField(choices=[('DIRECT_SELL', 'Direct Sell'), ('SELL_INTENT', 'Sell Intent'), ('BUY_NOW', 'Buy Now')], default='DIRECT_SELL', max_length=20)),
                ('price', models.DecimalField(decimal_places=9, help_text='Listing price in SOL', max_digits=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this listing is still active')),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this listing expires', null=True)),
                ('sold_at', models.DateTimeField(blank=True, help_text='When this NFT was sold', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(help_text='The NFT being listed', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='nft_data.nft')),
            ],
            options={
                'verbose_name': 'NFT Listing',
                'verbose_name_plural': 'NFT Listings',
                'ordering': ['-listed_at'],
                'indexes': [models.Index(fields=['seller', 'is_active'], name='marketplace_seller_efacf9_idx'), models.Index(fields=['nft', 'is_active'], name='marketplace_nft_id_dc2aca_idx'), models.Index(fields=['collection', 'is_active'], name='marketplace_collect_09aa57_idx'), models.Index(fields=['listing_type', 'is_active'], name='marketplace_listing_3059cb_idx')],
            },
        ),
    ]
