# Generated by Django 5.0.7 on 2025-11-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_bid_nftlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebid',
            name='amount',
            field=models.DecimalField(decimal_places=9, default=0.0, help_text='Bid amount in SOL', max_digits=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TransactionMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_signature', models.CharField(db_index=True, help_text='Solana transaction signature', max_length=88, unique=True)),
                ('action_type', models.CharField(choices=[('place_bid', 'Place Bid'), ('accept_bid', 'Accept Bid'), ('reject_bid', 'Reject Bid'), ('cancel_bid', 'Cancel Bid'), ('create_auction', 'Create Auction'), ('place_auction_bid', 'Place Auction Bid'), ('cancel_auction', 'Cancel Auction'), ('finalize_auction', 'Finalize Auction'), ('set_sell_intent', 'Set Sell Intent'), ('remove_sell_intent', 'Remove Sell Intent'), ('counter_offer', 'Counter Offer')], db_index=True, help_text='Type of marketplace action', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When transaction was submitted to RPC')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When transaction was confirmed on-chain', null=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='When transaction reached finality', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted to RPC'), ('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('FINALIZED', 'Finalized'), ('FAILED', 'Failed'), ('TIMEOUT', 'Confirmation timeout')], db_index=True, default='SUBMITTED', max_length=20)),
                ('confirmation_time_ms', models.IntegerField(blank=True, help_text='Time to confirm in milliseconds', null=True)),
                ('finalization_time_ms', models.IntegerField(blank=True, help_text='Time to finalize in milliseconds', null=True)),
                ('rpc_provider', models.CharField(blank=True, help_text='RPC provider used (helius, quicknode, etc.)', max_length=50)),
                ('nft_mint', models.CharField(blank=True, db_index=True, help_text='NFT involved in transaction', max_length=44)),
                ('user_wallet', models.CharField(blank=True, db_index=True, help_text='User wallet that initiated transaction', max_length=44)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of confirmation retry attempts')),
                ('metadata', models.JSONField(default=dict, help_text='Additional transaction context')),
            ],
            options={
                'verbose_name': 'Transaction Monitoring',
                'verbose_name_plural': 'Transaction Monitoring',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='marketplace_status_776ad5_idx'), models.Index(fields=['action_type', '-submitted_at'], name='marketplace_action__7abf83_idx'), models.Index(fields=['rpc_provider', '-submitted_at'], name='marketplace_rpc_pro_f1b209_idx'), models.Index(fields=['nft_mint', '-submitted_at'], name='marketplace_nft_min_6fba25_idx'), models.Index(fields=['user_wallet', '-submitted_at'], name='marketplace_user_wa_d99696_idx')],
            },
        ),
    ]
