# Generated by Django 5.0.7 on 2025-11-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_rename_sentiment_score_to_perception_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionvitality',
            name='perception_index',
            field=models.FloatField(default=0.5, help_text='Collection perception (0-1) - TODO: Not yet implemented'),
        ),
        migrations.AlterField(
            model_name='nftvitality',
            name='perception_index',
            field=models.FloatField(default=0.5, help_text='Community perception (0-1) - TODO: Not yet implemented'),
        ),
    ]
