# Generated by Django 5.0.7 on 2025-11-08 14:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_collectionvitality_perception_index_and_more'),
        ('nft_data', '0013_nft_active_auction_nft_asking_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerceptionGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.CharField(db_index=True, help_text='ID of the perception graph this node belongs to', max_length=100)),
                ('node_id', models.CharField(help_text='Unique identifier for this node within the graph', max_length=100)),
                ('node_type', models.CharField(help_text='Type of node (user, topic, community, hashtag, influencer, etc.)', max_length=50)),
                ('label', models.CharField(help_text='Human-readable label for this node', max_length=255)),
                ('influence_score', models.FloatField(default=0.0, help_text='Influence score of this node in the graph (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sentiment', models.CharField(blank=True, help_text='Sentiment associated with this node', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional node attributes from Parallel Lines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perception Graph Node',
                'verbose_name_plural': 'Perception Graph Nodes',
                'indexes': [models.Index(fields=['graph_id', 'node_type'], name='marketplace_graph_i_45bc26_idx'), models.Index(fields=['node_type', '-influence_score'], name='marketplace_node_ty_2d0a41_idx')],
                'unique_together': {('graph_id', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='PerceptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception_index', models.FloatField(help_text='Final Perception Index score (0-1) from IntuOne layer', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('submind_raw_score', models.FloatField(blank=True, help_text='Raw behavioral score from Submind layer (0-1) - unfiltered subconscious perception', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('submind_hidden_sentiment', models.CharField(blank=True, help_text='Hidden sentiment classification detected by Submind (positive, negative, neutral, mixed)', max_length=50, null=True)),
                ('manipulation_probability', models.FloatField(blank=True, help_text='Anti-gaming metric: Probability of manipulation detected (0-1, higher = more suspicious). Used to dampen perception scores when gaming is suspected.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('behavioral_pattern_flags', models.JSONField(blank=True, default=dict, help_text="Detected behavioral patterns from Submind analysis. Examples: {'bot_activity': true, 'wash_trading_influence': 0.08, 'coordinated_shilling': false}")),
                ('emotional_resonance', models.FloatField(blank=True, help_text='Emotional resonance score from IntuOne layer (0-1) - how strongly the community feels', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('language_tone', models.CharField(blank=True, help_text='Analyzed language tone from IntuOne (enthusiastic, cautious, fearful, euphoric, skeptical, etc.)', max_length=100, null=True)),
                ('community_awareness_score', models.FloatField(blank=True, help_text='Community awareness/engagement score from IntuOne (0-1) - how aware/engaged the community is', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('perception_graph_id', models.CharField(blank=True, db_index=True, help_text='ID of the perception graph topology this snapshot belongs to', max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence in this perception measurement (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('data_sources', models.JSONField(blank=True, default=list, help_text='List of data sources used (twitter, discord, reddit, on-chain, etc.)')),
                ('sample_size', models.IntegerField(blank=True, help_text='Number of data points analyzed for this snapshot', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this perception measurement was taken by Parallel Lines')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When TraitKeeper received this data')),
                ('source_type', models.CharField(choices=[('WEBHOOK', 'Webhook (Real-time)'), ('API_POLL', 'API Polling'), ('MANUAL', 'Manual Entry'), ('BACKFILL', 'Historical Backfill')], default='WEBHOOK', help_text='How this data was received', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, help_text='Raw JSON payload from Parallel Lines (for debugging/audit)', null=True)),
                ('collection', models.ForeignKey(blank=True, help_text="Collection this perception data applies to (e.g., 'DeGods sentiment')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perception_snapshots', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(blank=True, help_text="Specific NFT this perception data applies to (e.g., 'DeGods #4321 holder perception')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perception_snapshots', to='nft_data.nft')),
                ('trait_value', models.ForeignKey(blank=True, help_text="Specific trait this perception data applies to (e.g., 'Blue Background trait demand')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perception_snapshots', to='nft_data.traitvalue')),
            ],
            options={
                'verbose_name': 'Perception Snapshot',
                'verbose_name_plural': 'Perception Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParallelLinesWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When webhook was received')),
                ('endpoint', models.CharField(help_text='Webhook endpoint that received the call', max_length=255)),
                ('method', models.CharField(default='POST', help_text='HTTP method (usually POST)', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Request headers')),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('status', models.CharField(choices=[('SUCCESS', 'Successfully Processed'), ('FAILED', 'Processing Failed'), ('VALIDATION_ERROR', 'Validation Error'), ('AUTH_ERROR', 'Authentication Error'), ('DUPLICATE', 'Duplicate Data')], help_text='Processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('snapshots_created', models.IntegerField(default=0, help_text='Number of PerceptionSnapshot records created')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('perception_snapshot', models.ForeignKey(blank=True, help_text='Created PerceptionSnapshot (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='marketplace.perceptionsnapshot')),
            ],
            options={
                'verbose_name': 'Parallel Lines Webhook Log',
                'verbose_name_plural': 'Parallel Lines Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PerceptionAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], help_text='Aggregation time period', max_length=20)),
                ('period_start', models.DateTimeField(db_index=True, help_text='Start of aggregation period')),
                ('period_end', models.DateTimeField(help_text='End of aggregation period')),
                ('avg_perception_index', models.FloatField(help_text='Average perception index over period')),
                ('min_perception_index', models.FloatField(help_text='Minimum perception index in period')),
                ('max_perception_index', models.FloatField(help_text='Maximum perception index in period')),
                ('perception_volatility', models.FloatField(blank=True, help_text='Standard deviation of perception (volatility measure)', null=True)),
                ('avg_manipulation_probability', models.FloatField(blank=True, help_text='Average manipulation probability over period', null=True)),
                ('sample_count', models.IntegerField(help_text='Number of snapshots aggregated')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perception_aggregations', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perception_aggregations', to='nft_data.nft')),
                ('trait_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perception_aggregations', to='nft_data.traitvalue')),
            ],
            options={
                'verbose_name': 'Perception Aggregation',
                'verbose_name_plural': 'Perception Aggregations',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['collection', 'period', '-period_start'], name='marketplace_collect_d75c4f_idx'), models.Index(fields=['nft', 'period', '-period_start'], name='marketplace_nft_id_b4052d_idx'), models.Index(fields=['trait_value', 'period', '-period_start'], name='marketplace_trait_v_952148_idx')],
                'unique_together': {('collection', 'period', 'period_start'), ('nft', 'period', 'period_start'), ('trait_value', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PerceptionGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.CharField(db_index=True, help_text='ID of the perception graph this edge belongs to', max_length=100)),
                ('edge_type', models.CharField(help_text='Type of relationship (mentions, endorses, criticizes, discusses, etc.)', max_length=50)),
                ('weight', models.FloatField(default=1.0, help_text='Strength/weight of this relationship')),
                ('sentiment', models.CharField(blank=True, help_text='Sentiment of this relationship', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional edge attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(help_text='Source node of this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='marketplace.perceptiongraphnode')),
                ('target_node', models.ForeignKey(help_text='Target node of this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='marketplace.perceptiongraphnode')),
            ],
            options={
                'verbose_name': 'Perception Graph Edge',
                'verbose_name_plural': 'Perception Graph Edges',
                'indexes': [models.Index(fields=['graph_id', 'edge_type'], name='marketplace_graph_i_2889d6_idx'), models.Index(fields=['source_node', 'target_node'], name='marketplace_source__0a8070_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='perceptionsnapshot',
            index=models.Index(fields=['collection', '-timestamp'], name='marketplace_collect_dbea51_idx'),
        ),
        migrations.AddIndex(
            model_name='perceptionsnapshot',
            index=models.Index(fields=['nft', '-timestamp'], name='marketplace_nft_id_4666be_idx'),
        ),
        migrations.AddIndex(
            model_name='perceptionsnapshot',
            index=models.Index(fields=['trait_value', '-timestamp'], name='marketplace_trait_v_65a881_idx'),
        ),
        migrations.AddIndex(
            model_name='perceptionsnapshot',
            index=models.Index(fields=['perception_graph_id', '-timestamp'], name='marketplace_percept_24e3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='perceptionsnapshot',
            index=models.Index(fields=['-timestamp', 'perception_index'], name='marketplace_timesta_d78c81_idx'),
        ),
        migrations.AddConstraint(
            model_name='perceptionsnapshot',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('collection__isnull', False), ('nft__isnull', True), ('trait_value__isnull', True)), models.Q(('collection__isnull', True), ('nft__isnull', False), ('trait_value__isnull', True)), models.Q(('collection__isnull', True), ('nft__isnull', True), ('trait_value__isnull', False)), _connector='OR'), name='perception_snapshot_exactly_one_entity'),
        ),
        migrations.AddIndex(
            model_name='parallellineswebhooklog',
            index=models.Index(fields=['-received_at', 'status'], name='marketplace_receive_b846bd_idx'),
        ),
        migrations.AddIndex(
            model_name='parallellineswebhooklog',
            index=models.Index(fields=['status', '-received_at'], name='marketplace_status_b70d00_idx'),
        ),
    ]
