# Generated by Django 5.0.7 on 2025-06-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
