# Generated by Django 5.0.7 on 2025-06-10 19:10

import django.db.models.deletion
import django.utils.timezone
import nftmemories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0002_initial'),
        ('nft_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('LEGENDARY', 'Legendary')], default='LOW', help_text='Significance level for gamification purposes.', max_length=20)),
                ('user_interactions', models.JSONField(default=nftmemories.models.get_default_user_interactions, help_text='User engagement with the event (likes, comments, tributes, reactions).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Reference to the core NFT event in indexer.models.', on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='indexer.nftevent')),
            ],
            options={
                'verbose_name': 'Collection Event',
                'verbose_name_plural': 'Collection Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='nftmemories_event_i_79d1e3_idx'), models.Index(fields=['significance'], name='nftmemories_signifi_79b1de_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionRaritySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_supply', models.IntegerField()),
                ('rarity_base', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rarity_snapshots', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Collection Rarity Snapshot',
                'verbose_name_plural': 'Collection Rarity Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['collection', 'timestamp'], name='nftmemories_collect_01bfb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='NFTBurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='NFT name at the time of burning.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='NFT description at the time of burning.')),
                ('image_url', models.URLField(blank=True, help_text='Image URL at the time of burning.', max_length=500)),
                ('number', models.IntegerField(blank=True, help_text='NFT number (e.g., #123 in the collection).', null=True)),
                ('rarity', models.JSONField(default=dict, help_text="Rarity details (e.g., {'trait1': {'value': 'value1', 'rarity': 5.0}}).")),
                ('reason', models.TextField(blank=True, help_text='Reason for the burn, if known or provided by the user.')),
                ('reason_is_approved', models.BooleanField(default=False, help_text='Whether the user-provided reason has been approved by a moderator.')),
                ('user_interactions', models.JSONField(default=nftmemories.models.get_default_user_interactions, help_text='User engagement with the burned NFT (likes, comments, tributes, reactions).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.ForeignKey(blank=True, help_text='User who added the reason, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('burn_event', models.ForeignKey(help_text='Reference to the core burn event in indexer.models.', on_delete=django.db.models.deletion.CASCADE, related_name='memory_burns', to='indexer.burnevent')),
            ],
            options={
                'verbose_name': 'NFT Burn',
                'verbose_name_plural': 'NFT Burns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['burn_event'], name='nftmemories_burn_ev_b49e62_idx')],
            },
        ),
    ]
