# Generated by Django 5.0.7 on 2025-10-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftmemories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
