# Generated by Django 5.0.7 on 2025-05-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(default='f90c50ea6cb2404e8640e73619107039', max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the external user associated with this token.', max_length=254)),
                ('expires_at', models.DateTimeField(blank=True, help_text='The date and time when the token expires. Leave blank for no expiry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The admin user who created this token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
