# Generated by Django 5.0.7 on 2025-05-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='118cb785a3574bcd8797a81908f57749', max_length=40, primary_key=True, serialize=False),
        ),
    ]
