# Generated by Django 5.0.7 on 2025-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0002_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='a5fabdf87aaf4a63b64413e3c0620b23', max_length=40, primary_key=True, serialize=False),
        ),
    ]
