# Generated by Django 5.0.7 on 2025-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0003_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='d181a45904c245a784850d074f482c4f', max_length=40, primary_key=True, serialize=False),
        ),
    ]
