# Generated by Django 5.0.7 on 2025-05-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0004_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='ac951cfcbfb042d4b95dd83404b8690b', max_length=40, primary_key=True, serialize=False),
        ),
    ]
