# Generated by Django 5.0.7 on 2025-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0005_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='cd880097a18a4f34ae5d8715d43a65ea', max_length=40, primary_key=True, serialize=False),
        ),
    ]
