# Generated by Django 5.0.7 on 2025-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0006_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='e5d7e13374f5453287b05f0a5e830fe7', max_length=40, primary_key=True, serialize=False),
        ),
    ]
