# Generated by Django 5.0.7 on 2025-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0007_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='e76f66f109f5405b83ef0b9ba2a79af7', max_length=40, primary_key=True, serialize=False),
        ),
    ]
