# Generated by Django 5.0.7 on 2025-06-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0008_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='22b7d84fc10f41a5a5cda0b16e934e15', max_length=40, primary_key=True, serialize=False),
        ),
    ]
