# Generated by Django 5.0.7 on 2025-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0009_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='939b36cc80d342eab7c278b7f35cff9e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
