# Generated by Django 5.0.7 on 2025-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0011_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='cd2324cad4074fefa8045869a77c3ec1', max_length=40, primary_key=True, serialize=False),
        ),
    ]
