# Generated by Django 5.0.7 on 2025-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0012_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='6480ea77da7140dd872c6218364ff6fb', max_length=40, primary_key=True, serialize=False),
        ),
    ]
