# Generated by Django 5.0.7 on 2025-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0013_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='7c8724052d0340058f62f2abeb5c33a7', max_length=40, primary_key=True, serialize=False),
        ),
    ]
