# Generated by Django 5.0.7 on 2025-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0014_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='f3eb18f0706543b8abf0748381f75442', max_length=40, primary_key=True, serialize=False),
        ),
    ]
