# Generated by Django 5.0.7 on 2025-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0015_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='eeaf6c99a4cc4a3e8c819bd936833efb', max_length=40, primary_key=True, serialize=False),
        ),
    ]
