# Generated by Django 5.0.7 on 2025-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0016_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='32de223e6e604075a2e02452829fafae', max_length=40, primary_key=True, serialize=False),
        ),
    ]
