# Generated by Django 5.0.7 on 2025-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0017_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='8fad137f0b8c47f588bbb3d2f8b6dad5', max_length=40, primary_key=True, serialize=False),
        ),
    ]
