# Generated by Django 5.0.7 on 2025-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0018_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='0806502cbcdd4773a772c55f283526c6', max_length=40, primary_key=True, serialize=False),
        ),
    ]
