# Generated by Django 5.0.7 on 2025-06-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0019_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='3b7b99a2d28f482599ef68ebffdd71a2', max_length=40, primary_key=True, serialize=False),
        ),
    ]
