# Generated by Django 5.0.7 on 2025-06-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0020_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='c64516343b98472fa72afc2598a3f154', max_length=40, primary_key=True, serialize=False),
        ),
    ]
