# Generated by Django 5.0.7 on 2025-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0021_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='3090ef32743e460c8f04bab6a6d88a64', max_length=40, primary_key=True, serialize=False),
        ),
    ]
