# Generated by Django 5.0.7 on 2025-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0023_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='91f243b621ac4f7ab97957b275bc5ba3', max_length=40, primary_key=True, serialize=False),
        ),
    ]
