# Generated by Django 5.0.7 on 2025-06-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0024_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='621c34bb67824e599f3e72c0ec65641f', max_length=40, primary_key=True, serialize=False),
        ),
    ]
