# Generated by Django 5.0.7 on 2025-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0026_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='5d23b8616710493790758961832ace8c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
