# Generated by Django 5.0.7 on 2025-06-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0027_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='42844c835a434abe9bd96e2bee21e0f0', max_length=40, primary_key=True, serialize=False),
        ),
    ]
