# Generated by Django 5.0.7 on 2025-06-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0028_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='e3a20f46a2e046aa973dc75229c8e18b', max_length=40, primary_key=True, serialize=False),
        ),
    ]
