# Generated by Django 5.0.7 on 2025-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0029_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='bbd862afa4dc4170b9a002c85bdfce65', max_length=40, primary_key=True, serialize=False),
        ),
    ]
