# Generated by Django 5.0.7 on 2025-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0030_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='84cc66de9d8b4b97bc5b1141d8498db3', max_length=40, primary_key=True, serialize=False),
        ),
    ]
