# Generated by Django 5.0.7 on 2025-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0031_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='5fc6b3e059c44fbeb2b3985d2340112b', max_length=40, primary_key=True, serialize=False),
        ),
    ]
