# Generated by Django 5.0.7 on 2025-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0032_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='2ca8d0843263451bbe9f667b28b6f0fa', max_length=40, primary_key=True, serialize=False),
        ),
    ]
