# Generated by Django 5.0.7 on 2025-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0033_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='f0b1d261e4fc4c5b9067ae9232702a50', max_length=40, primary_key=True, serialize=False),
        ),
    ]
