# Generated by Django 5.0.7 on 2025-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0034_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='9eb9b75f9eb04887bce8ce478f88d3e4', max_length=40, primary_key=True, serialize=False),
        ),
    ]
