# Generated by Django 5.0.7 on 2025-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0035_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='99a7d9a0cbb14b0988077e92305d3268', max_length=40, primary_key=True, serialize=False),
        ),
    ]
