# Generated by Django 5.0.7 on 2025-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0036_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='c36905f4a0024555898d3df6fb273887', max_length=40, primary_key=True, serialize=False),
        ),
    ]
