# Generated by Django 5.0.7 on 2025-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0037_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='7411b736e8814c7b97bcacecabb51ad6', max_length=40, primary_key=True, serialize=False),
        ),
    ]
