# Generated by Django 5.0.7 on 2025-10-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0038_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='ba418dd09eaa4a0da3b288affd067f25', max_length=40, primary_key=True, serialize=False),
        ),
    ]
