# Generated by Django 5.0.7 on 2025-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0039_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='bfeb9663de2748cbb2edb2739e99245e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
