# Generated by Django 5.0.7 on 2025-10-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0040_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='bff6864b69d34913b5410d8f67a23a1f', max_length=40, primary_key=True, serialize=False),
        ),
    ]
