# Generated by Django 5.0.7 on 2025-10-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0041_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='2058f9192dc34b2b82306148969f59ac', max_length=40, primary_key=True, serialize=False),
        ),
    ]
