# Generated by Django 5.0.7 on 2025-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0042_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='da78384b3c3f414ca54908faf586e02d', max_length=40, primary_key=True, serialize=False),
        ),
    ]
