# Generated by Django 5.0.7 on 2025-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0043_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='a60fc7767e1e4cbf979156d0084f463c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
