# Generated by Django 5.0.7 on 2025-10-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0044_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='39647855817643d5847b1d5f8e82aeea', max_length=40, primary_key=True, serialize=False),
        ),
    ]
