# Generated by Django 5.0.7 on 2025-10-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0045_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='c3ff5caaf3b245648d1a82579b6b86ac', max_length=40, primary_key=True, serialize=False),
        ),
    ]
