# Generated by Django 5.0.7 on 2025-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0046_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='cdf9f5ea1f074730a35e8f32886bf50e', max_length=40, primary_key=True, serialize=False),
        ),
    ]
