# Generated by Django 5.0.7 on 2025-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0047_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='ccfb3861dadf4e6f8bcdbb6f05de827c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
