# Generated by Django 5.0.7 on 2025-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0048_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='98f767860c354325ada2108687d2d518', max_length=40, primary_key=True, serialize=False),
        ),
    ]
