# Generated by Django 5.0.7 on 2025-11-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0049_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='58fa5ab746284fa8b8fcb5f76e8686c8', max_length=40, primary_key=True, serialize=False),
        ),
    ]
