# Generated by Django 5.0.7 on 2025-11-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0050_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='8ec3108fa24d4107a4a85a96dbd292ab', max_length=40, primary_key=True, serialize=False),
        ),
    ]
