# Generated by Django 5.0.7 on 2025-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0051_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='34c92212063f4c56b520e2dc4624a9e4', max_length=40, primary_key=True, serialize=False),
        ),
    ]
