# Generated by Django 5.0.7 on 2025-11-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0052_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='e7a388037a90424f8b75339cad6c371d', max_length=40, primary_key=True, serialize=False),
        ),
    ]
