# Generated by Django 5.0.7 on 2025-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0053_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='a519310b15c74220973f93ec245cbbaa', max_length=40, primary_key=True, serialize=False),
        ),
    ]
