# Generated by Django 5.0.7 on 2025-11-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0054_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='531f114d083043a281cdcb5175052207', max_length=40, primary_key=True, serialize=False),
        ),
    ]
