# Generated by Django 5.1.10 on 2025-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitkeeper', '0055_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='ea38e23076be4a1ba1671bf5f832ae4c', max_length=40, primary_key=True, serialize=False),
        ),
    ]
