# Generated by Django 5.0.7 on 2025-06-10 19:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=44, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly name for the collection, set by the creator.', max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('symbol', models.CharField(blank=True, default='', max_length=50)),
                ('creator_address', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(default=True, help_text='Whether the collection is listed for public viewing.')),
                ('source', models.CharField(default='webhook', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NFT Collection',
                'verbose_name_plural': 'NFT Collections',
                'ordering': ['-created_at'],
                'permissions': [('mark_featured_nftcollection', 'Can mark NFT collections as featured'), ('unmark_featured_nftcollection', 'Can unmark NFT collections as featured'), ('fetch_onchain_nftcollection', 'Can fetch onchain data for NFT collections'), ('update_stats_nftcollection', 'Can update stats for NFT collections')],
            },
        ),
        migrations.CreateModel(
            name='HighProfileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('traits', models.JSONField(default=dict)),
                ('high_profile_score', models.FloatField(default=0.0)),
                ('value_factor', models.FloatField(default=0.0)),
                ('wallet_factor', models.FloatField(default=0.0)),
                ('timing_factor', models.FloatField(default=0.0)),
                ('historical_factor', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(help_text='Reference to the NFT event (SALE).', on_delete=django.db.models.deletion.CASCADE, to='indexer.nftevent')),
            ],
            options={
                'verbose_name': 'High Profile Transfer',
                'verbose_name_plural': 'High Profile Transfers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mint_address', models.CharField(max_length=44, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('creator_address', models.CharField(blank=True, max_length=44)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mint_address'], name='nft_data_pe_mint_ad_ce808f_idx'), models.Index(fields=['status'], name='nft_data_pe_status_8ea551_idx')],
            },
        ),
        migrations.CreateModel(
            name='TraitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_types', to='nft_data.nftcollection')),
            ],
            options={
                'verbose_name': 'Trait Type',
                'verbose_name_plural': 'Trait Types',
                'permissions': [('recalculate_counts_traittype', 'Can recalculate counts for trait types')],
                'unique_together': {('name', 'collection')},
            },
        ),
        migrations.CreateModel(
            name='TraitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('rarity', models.FloatField(default=0.0)),
                ('trait_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='nft_data.traittype')),
            ],
            options={
                'verbose_name': 'Trait Value',
                'verbose_name_plural': 'Trait Values',
                'permissions': [('recalculate_rarity_traitvalue', 'Can recalculate rarity for trait values')],
                'unique_together': {('trait_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='TopTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_score', models.FloatField(default=0.0)),
                ('volume_score', models.FloatField(default=0.0)),
                ('count_score', models.FloatField(default=0.0)),
                ('combined_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.nftcollection')),
                ('trait_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traittype')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traitvalue')),
            ],
            options={
                'verbose_name': 'Top Trait',
                'verbose_name_plural': 'Top Traits',
                'ordering': ['-combined_score'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCollectionTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('rarity', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.nftcollection')),
                ('trait_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traittype')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traitvalue')),
            ],
            options={
                'verbose_name': 'Featured Collection Trait',
                'verbose_name_plural': 'Featured Collection Traits',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='TrendingTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('trend_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traittype')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft_data.traitvalue')),
            ],
            options={
                'verbose_name': 'Trending Trait',
                'verbose_name_plural': 'Trending Traits',
                'ordering': ['-trend_score'],
            },
        ),
        migrations.CreateModel(
            name='WalletProminence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('transaction_volume', models.FloatField(default=0.0)),
                ('collections_count', models.IntegerField(default=0)),
                ('high_value_transactions', models.IntegerField(default=0)),
                ('prominence_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['address'], name='nft_data_wa_address_769782_idx'), models.Index(fields=['prominence_score'], name='nft_data_wa_promine_e97caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionSweepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_address', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('num_items', models.IntegerField()),
                ('total_volume', models.FloatField()),
                ('average_price', models.FloatField()),
                ('pre_sweep_floor', models.FloatField()),
                ('post_sweep_floor', models.FloatField()),
                ('price_movement', models.FloatField()),
                ('target_traits', models.JSONField(blank=True, null=True)),
                ('nft_mints', models.JSONField()),
                ('significance_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_events', to='nft_data.nftcollection')),
            ],
            options={
                'indexes': [models.Index(fields=['collection', 'significance_score'], name='nft_data_co_collect_8c14e0_idx'), models.Index(fields=['buyer_address', 'start_time'], name='nft_data_co_buyer_a_3e7cfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('mint_address', models.CharField(max_length=44, primary_key=True, serialize=False)),
                ('token_address', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('traits', models.JSONField(blank=True, default=dict)),
                ('number', models.IntegerField(blank=True, help_text='The sequence or edition number of the NFT in the collection.', null=True)),
                ('owner', models.CharField(blank=True, help_text='The wallet address of the current owner.', max_length=44, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highest_bid', models.FloatField(blank=True, default=0.0)),
                ('highest_bidder', models.CharField(blank=True, max_length=44)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True)),
                ('creators', models.ManyToManyField(related_name='nfts', to='nft_data.creator')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='nft_data.nftcollection')),
                ('trait_values', models.ManyToManyField(related_name='nfts', to='nft_data.traitvalue')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFTs',
                'permissions': [('refresh_traits_nft', 'Can refresh traits for NFTs'), ('clear_auction_nft', 'Can clear auction for NFTs')],
                'indexes': [models.Index(fields=['collection', 'owner'], name='nft_data_nf_collect_a84131_idx')],
            },
        ),
    ]
