# Generated by Django 5.0.7 on 2025-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='Whether NFT is currently listed anywhere'),
        ),
        migrations.AddField(
            model_name='nft',
            name='listing_marketplace',
            field=models.CharField(blank=True, help_text='Source marketplace of cheapest listing', max_length=50),
        ),
        migrations.AddField(
            model_name='nft',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Cheapest listing price (mapped from indexer)', max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='nft',
            index=models.Index(fields=['collection', 'is_listed', 'listing_price'], name='nft_data_nf_collect_c339c3_idx'),
        ),
    ]
