# Generated by Django 5.0.7 on 2025-06-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0006_crossmarketplacecomparison_activity_distribution_magic_eden_and_more'),
        ('nft_data', '0002_nft_is_listed_nft_listing_marketplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highprofiletransfer',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nft_data.nftcollection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highprofiletransfer',
            name='nft',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nft_data.nft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toptrait',
            name='nfts',
            field=models.ManyToManyField(related_name='top_traits', to='nft_data.nft'),
        ),
        migrations.AddField(
            model_name='trendingtrait',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nft_data.nftcollection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingtrait',
            name='nfts',
            field=models.ManyToManyField(related_name='trending_traits', to='nft_data.nft'),
        ),
        migrations.AddIndex(
            model_name='highprofiletransfer',
            index=models.Index(fields=['collection', 'high_profile_score'], name='nft_data_hi_collect_d2e9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='highprofiletransfer',
            index=models.Index(fields=['nft', 'updated_at'], name='nft_data_hi_nft_id_c11758_idx'),
        ),
        migrations.AddIndex(
            model_name='highprofiletransfer',
            index=models.Index(fields=['event'], name='nft_data_hi_event_i_c0556c_idx'),
        ),
        migrations.AddIndex(
            model_name='toptrait',
            index=models.Index(fields=['collection', 'combined_score'], name='nft_data_to_collect_96def8_idx'),
        ),
        migrations.AddIndex(
            model_name='toptrait',
            index=models.Index(fields=['trait_type', 'trait_value'], name='nft_data_to_trait_t_de14c1_idx'),
        ),
        migrations.AddIndex(
            model_name='toptrait',
            index=models.Index(fields=['updated_at'], name='nft_data_to_updated_c6e52a_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtrait',
            index=models.Index(fields=['collection', 'trend_score'], name='nft_data_tr_collect_7180c3_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtrait',
            index=models.Index(fields=['trait_type', 'trait_value'], name='nft_data_tr_trait_t_ec4c10_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtrait',
            index=models.Index(fields=['updated_at'], name='nft_data_tr_updated_4a7e25_idx'),
        ),
    ]
