# Generated by Django 5.0.7 on 2025-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0003_highprofiletransfer_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_burned',
            field=models.BooleanField(default=False),
        ),
    ]
