# Generated by Django 5.0.7 on 2025-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0004_nft_is_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nft',
            name='current_highest_bid',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='last_bid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
