# Generated by Django 5.0.7 on 2025-06-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0005_nft_bid_count_nft_current_highest_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='display_name',
            field=models.CharField(blank=True, help_text="Clean, user-friendly collection name. Generated from 'name' or set by creators.", max_length=255),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='name',
            field=models.CharField(help_text='Raw collection name from blockchain', max_length=255),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Magic Eden compatible slug generated from display_name (lowercase with underscores)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='symbol',
            field=models.CharField(blank=True, default='', help_text='Collection symbol (different from slug)', max_length=50),
        ),
    ]
