# Generated by Django 5.0.7 on 2025-07-27 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0006_nftcollection_display_name_alter_nftcollection_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='api_quota_limit',
            field=models.IntegerField(default=30, help_text='Daily API quota allocation based on priority tier'),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='daily_api_calls',
            field=models.IntegerField(default=0, help_text='API calls used today for this collection'),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='last_activity_detected',
            field=models.DateTimeField(blank=True, help_text='Last time trading activity was detected for performance tracking', null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='last_api_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time API quota was reset (daily)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='last_priority_update',
            field=models.DateTimeField(blank=True, help_text='When priority score was last calculated', null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='next_update_due',
            field=models.DateTimeField(blank=True, help_text='When next update is scheduled based on priority tier', null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='Composite performance score (0-100) based on volume, activity, and user engagement'),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='priority_tier',
            field=models.CharField(choices=[('VIP', 'VIP - High Activity (60% quota)'), ('ACTIVE', 'Active - Medium Activity (30% quota)'), ('INACTIVE', 'Inactive - Low Activity (10% quota)')], default='ACTIVE', help_text='Auto-assigned priority tier based on performance score for API quota allocation', max_length=10),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='update_frequency_minutes',
            field=models.IntegerField(default=120, help_text='How often to update this collection (minutes) based on priority'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['priority_tier', 'priority_score'], name='nft_data_nf_priorit_a37c57_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['next_update_due'], name='nft_data_nf_next_up_5ec694_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['last_activity_detected'], name='nft_data_nf_last_ac_c0bb58_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['priority_tier', 'last_activity_detected'], name='nft_data_nf_priorit_85ed11_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['daily_api_calls', 'api_quota_limit'], name='nft_data_nf_daily_a_611224_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['priority_tier', 'next_update_due'], name='nft_data_nf_priorit_1c8ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['last_priority_update'], name='nft_data_nf_last_pr_ae1134_idx'),
        ),
    ]
