# Generated by Django 5.0.7 on 2025-08-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0010_remove_nftevent_collection_remove_nftevent_nft_and_more'),
        ('nft_data', '0007_nftcollection_api_quota_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highprofiletransfer',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_profile_transfers', to='nft_data.nftcollection'),
        ),
        migrations.AlterField(
            model_name='highprofiletransfer',
            name='event',
            field=models.ForeignKey(help_text='Reference to the NFT event (SALE).', on_delete=django.db.models.deletion.CASCADE, related_name='high_profile_transfers', to='indexer.nftevent'),
        ),
        migrations.AlterField(
            model_name='highprofiletransfer',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_profile_transfers', to='nft_data.nft'),
        ),
    ]
