# Generated by Django 5.0.7 on 2025-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0008_alter_highprofiletransfer_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='vitality_score',
            field=models.FloatField(default=0.0, help_text='NFT-specific Vitality Score'),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='last_vitality_update',
            field=models.DateTimeField(blank=True, help_text='When vitality score was last calculated', null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='vitality_score',
            field=models.FloatField(default=0.0, help_text='Custom NFT Vitality Score (0-100) based on holder quality, sentiment, etc.'),
        ),
        migrations.AddIndex(
            model_name='nftcollection',
            index=models.Index(fields=['vitality_score', 'last_vitality_update'], name='nft_data_nf_vitalit_50f954_idx'),
        ),
    ]
