# Generated by Django 5.0.7 on 2025-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0010_remove_collectionsweepevent_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
