# Generated by Django 5.0.7 on 2025-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0011_nftcollection_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='The public, fixed price in SOL for an instant buy.', max_digits=20, null=True),
        ),
    ]
