# Generated by Django 5.0.7 on 2025-10-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_marketplacetransaction_privatebid'),
        ('nft_data', '0012_nft_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='active_auction',
            field=models.ForeignKey(blank=True, help_text='Reference to active auction if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nft_in_auction', to='marketplace.auctionevent'),
        ),
        migrations.AddField(
            model_name='nft',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=9, help_text="Owner's asking price in SOL", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='has_buy_price',
            field=models.BooleanField(default=False, help_text='Whether NFT has a set buy-now price'),
        ),
        migrations.AddField(
            model_name='nft',
            name='has_sell_intent',
            field=models.BooleanField(default=False, help_text='Whether owner has expressed intent to sell'),
        ),
        migrations.AddField(
            model_name='nft',
            name='is_open_to_offers',
            field=models.BooleanField(default=False, help_text='Whether NFT is open to receiving private offers'),
        ),
        migrations.AddField(
            model_name='nft',
            name='vitality_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NFT vitality score for pricing suggestions', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='Whether NFT is listed for sale'),
        ),
    ]
