# Generated by Django 5.1.10 on 2025-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_data', '0013_nft_active_auction_nft_asking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcollection',
            name='status',
            field=models.CharField(choices=[('validating', 'Validating'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='validating', max_length=20),
        ),
    ]
