# Generated by Django 5.0.7 on 2025-11-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0006_delete_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this secret', max_length=100, unique=True)),
                ('secret_type', models.CharField(choices=[('PROGRAM_AUTHORITY', 'Program Authority Private Key'), ('RPC_API_KEY', 'RPC API Key'), ('WEBHOOK_SECRET', 'Webhook Secret'), ('ENCRYPTION_KEY', 'Encryption Key'), ('API_TOKEN', 'API Token')], help_text='Type of secret being stored', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this secret is used for')),
                ('encrypted_value', models.BinaryField(help_text='Fernet-encrypted secret value')),
                ('encryption_key_id', models.CharField(default='v1', help_text='Which encryption key version was used (for key rotation)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='When was this secret last decrypted', null=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this secret has been decrypted')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this secret is currently active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this secret', null=True)),
                ('created_by', models.ForeignKey(help_text='Admin user who created this secret', on_delete=django.db.models.deletion.PROTECT, related_name='created_secrets', to='admin_panel.adminuser')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='Admin user who last modified this secret', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_secrets', to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'Encrypted Secret',
                'verbose_name_plural': 'Encrypted Secrets',
                'permissions': [('view_encrypted_secret', 'Can view encrypted secrets'), ('decrypt_secret', 'Can decrypt secrets'), ('rotate_secret', 'Can rotate secret keys')],
            },
        ),
        migrations.CreateModel(
            name='SecretAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DECRYPTED', 'Decrypted'), ('ENCRYPTED', 'Encrypted'), ('ROTATED', 'Rotated'), ('VIEWED', 'Viewed (metadata only)'), ('FAILED_DECRYPT', 'Failed Decryption Attempt')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('requesting_component', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='admin_secure.encryptedsecret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'Secret Access Log',
                'verbose_name_plural': 'Secret Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='encryptedsecret',
            index=models.Index(fields=['secret_type', 'is_active'], name='admin_secur_secret__7f1499_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedsecret',
            index=models.Index(fields=['created_at'], name='admin_secur_created_c9a801_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccesslog',
            index=models.Index(fields=['secret', '-timestamp'], name='admin_secur_secret__8241ca_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccesslog',
            index=models.Index(fields=['user', '-timestamp'], name='admin_secur_user_id_0fa2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccesslog',
            index=models.Index(fields=['action', '-timestamp'], name='admin_secur_action_11093b_idx'),
        ),
    ]
