# Generated by Django 5.0.7 on 2025-10-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletprofile',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'Wallet Profile', 'verbose_name_plural': 'Wallet Profiles'},
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary wallet for this user'),
        ),
        migrations.AlterField(
            model_name='walletprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
