# Generated by Django 5.0.7 on 2025-10-29 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('ERROR', 'Error')], default='HEALTHY', max_length=20)),
                ('cpu_percent', models.FloatField(default=0, help_text='CPU usage percentage')),
                ('memory_percent', models.FloatField(default=0, help_text='Memory usage percentage')),
                ('disk_percent', models.FloatField(default=0, help_text='Disk usage percentage')),
                ('indexer_running', models.BooleanField(default=False)),
                ('redis_connected', models.BooleanField(default=False)),
                ('database_connected', models.BooleanField(default=True)),
                ('active_tasks', models.IntegerField(default=0, help_text='Currently active background tasks')),
                ('failed_tasks_24h', models.IntegerField(default=0, help_text='Failed tasks in last 24 hours')),
                ('successful_tasks_24h', models.IntegerField(default=0, help_text='Successful tasks in last 24 hours')),
                ('last_successful_index', models.DateTimeField(blank=True, null=True)),
                ('events_indexed_24h', models.IntegerField(default=0, help_text='Events indexed in last 24 hours')),
                ('indexing_lag_minutes', models.FloatField(default=0, help_text='Minutes behind blockchain')),
                ('active_listings_count', models.IntegerField(default=0)),
                ('sales_24h', models.IntegerField(default=0)),
                ('volume_24h', models.DecimalField(decimal_places=4, default=0, help_text='SOL', max_digits=20)),
                ('unique_traders_24h', models.IntegerField(default=0)),
                ('active_users_24h', models.IntegerField(default=0, help_text='Users active in last 24 hours')),
                ('new_users_24h', models.IntegerField(default=0, help_text='New users in last 24 hours')),
                ('total_users', models.IntegerField(default=0)),
                ('total_nfts_tracked', models.IntegerField(default=0)),
                ('total_collections_tracked', models.IntegerField(default=0)),
                ('collections_updated_24h', models.IntegerField(default=0)),
                ('alerts', models.JSONField(default=list, help_text='List of current alerts')),
                ('alert_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metrics and context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ecosystem Health',
                'verbose_name_plural': 'Ecosystem Health Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_heal_timesta_68a206_idx'), models.Index(fields=['status', '-timestamp'], name='system_heal_status_cc103c_idx'), models.Index(fields=['-created_at'], name='system_heal_created_0b604e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('INDEXING_SPEED', 'Indexing Speed (events/min)'), ('API_RESPONSE_TIME', 'API Response Time (ms)'), ('DATABASE_QUERY_TIME', 'Database Query Time (ms)'), ('CACHE_HIT_RATE', 'Cache Hit Rate (%)'), ('CONCURRENT_USERS', 'Concurrent Users'), ('TASK_COMPLETION_TIME', 'Task Completion Time (s)')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.FloatField(help_text='Metric value')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('component', models.CharField(blank=True, help_text='Specific component or endpoint', max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='system_heal_metric__be4bef_idx'), models.Index(fields=['component', '-timestamp'], name='system_heal_compone_73ed31_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('INDEXER', 'Indexer Service'), ('DATABASE', 'Database'), ('REDIS', 'Redis Cache'), ('MARKETPLACE', 'Marketplace'), ('NOTIFICATIONS', 'Notifications'), ('SOLANA_RPC', 'Solana RPC'), ('EXTERNAL_API', 'External API')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_healthy', models.BooleanField(default=True)),
                ('response_time_ms', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict, help_text='Additional check details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Health Check',
                'verbose_name_plural': 'Service Health Checks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service_type', '-timestamp'], name='system_heal_service_6709b3_idx'), models.Index(fields=['is_healthy', '-timestamp'], name='system_heal_is_heal_496f95_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('category', models.CharField(choices=[('RESOURCE', 'Resource Usage'), ('SERVICE', 'Service Status'), ('DATA', 'Data Integrity'), ('SECURITY', 'Security'), ('PERFORMANCE', 'Performance')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('source_component', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecosystem_health', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to='system_health.ecosystemhealth')),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['is_resolved', '-triggered_at'], name='system_heal_is_reso_212ff1_idx'), models.Index(fields=['alert_level', '-triggered_at'], name='system_heal_alert_l_d5ee06_idx'), models.Index(fields=['category', '-triggered_at'], name='system_heal_categor_23963e_idx')],
            },
        ),
    ]
