# Generated by Django 5.0.7 on 2025-11-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_health', '0002_healthsharetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='healthsharetoken',
            new_name='system_heal_token_866b2b_idx',
            old_name='system_heal_token_8f5c3d_idx',
        ),
    ]
