# Generated by Django 5.1.10 on 2025-12-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_health', '0004_serviceuptime'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceuptime',
            new_name='system_heal_service_8bf06b_idx',
            old_name='system_heal_service_6fc2a0_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceuptime',
            new_name='system_heal_date_957c63_idx',
            old_name='system_heal_date_c7d421_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceuptime',
            new_name='system_heal_uptime__03ed43_idx',
            old_name='system_heal_uptime__e42b18_idx',
        ),
    ]
