# Generated by Django 5.0.7 on 2025-06-10 19:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('auction_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('mint_address', models.CharField(db_index=True, max_length=44)),
                ('creator', models.CharField(max_length=44)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('starting_price', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('current_bid', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('current_bidder', models.CharField(blank=True, max_length=44, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=44, null=True)),
                ('final_price', models.DecimalField(decimal_places=9, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BurnEvent',
            fields=[
                ('burn_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('mint_address', models.CharField(db_index=True, max_length=44)),
                ('burner', models.CharField(blank=True, max_length=44)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Burn Event',
                'verbose_name_plural': 'Burn Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CollectionMarketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_address', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('magic_eden', 'Magic Eden'), ('tensor', 'Tensor'), ('blockchain', 'Blockchain'), ('site', 'Your Site'), ('aggregated', 'Aggregated')], default='aggregated', max_length=20)),
                ('floor_price', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('average_price_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('total_supply', models.IntegerField(default=0)),
                ('listed_count', models.IntegerField(default=0)),
                ('number_of_holders', models.IntegerField(default=0)),
                ('volume_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('volume_7d', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('volume_30d', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('total_volume', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('velocity_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('performance_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_response_time', models.FloatField(blank=True, null=True)),
                ('data_freshness', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('manage_collectionmarketstats', 'Can manage collection market stats')],
            },
        ),
        migrations.CreateModel(
            name='FailedTransaction',
            fields=[
                ('event_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('collection_address', models.CharField(db_index=True, max_length=44)),
                ('event_data', models.JSONField()),
                ('error_message', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('last_retry', models.DateTimeField(blank=True, null=True)),
                ('provider_name', models.CharField(default='unknown', max_length=50)),
                ('signature', models.CharField(blank=True, max_length=88)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('retry_failedtransaction', 'Can retry failed transactions'), ('manage_failedtransaction', 'Can manage failed transactions')],
            },
        ),
        migrations.CreateModel(
            name='NFTEvent',
            fields=[
                ('event_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('collection_address', models.CharField(db_index=True, max_length=44)),
                ('mint_address', models.CharField(db_index=True, max_length=44)),
                ('event_type', models.CharField(choices=[('NFT_SALE', 'NFT Sale'), ('NFT_LISTING', 'NFT Listing'), ('NFT_CANCEL_LISTING', 'NFT Cancel Listing'), ('NFT_BID', 'NFT Bid'), ('NFT_BID_CANCELLED', 'NFT Bid Cancelled'), ('NFT_MINT', 'NFT Mint'), ('TRANSFER', 'Transfer'), ('BURN', 'Burn'), ('COMPRESSED_NFT_MINT', 'Compressed NFT Mint'), ('COMPRESSED_NFT_TRANSFER', 'Compressed NFT Transfer'), ('COMPRESSED_NFT_BURN', 'Compressed NFT Burn')], max_length=50)),
                ('marketplace', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=9, max_digits=20, null=True)),
                ('buyer', models.CharField(blank=True, max_length=44, null=True)),
                ('seller', models.CharField(blank=True, max_length=44, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', help_text='Status for listings and bids (active, cancelled, completed).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_signature', models.CharField(db_index=True, max_length=88, unique=True)),
                ('amount', models.DecimalField(decimal_places=9, default=Decimal('0.001'), max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('SALE', 'Sale'), ('AUCTION', 'Auction')], max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TraitEvent',
            fields=[
                ('event_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('mint_address', models.CharField(db_index=True, max_length=44)),
                ('action', models.CharField(choices=[('ADDED', 'Added'), ('UPDATED', 'Updated'), ('REMOVED', 'Removed')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('manage_traitevent', 'Can manage trait events')],
            },
        ),
        migrations.CreateModel(
            name='TraitPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_score', models.FloatField(default=0.0)),
                ('avg_sale_price', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('premium_score', models.FloatField(default=0.0)),
                ('velocity_score', models.FloatField(default=0.0)),
                ('momentum_score', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
