# Generated by Django 5.0.7 on 2025-06-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0001_initial'),
        ('nft_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionevent',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='nft_data.nft'),
        ),
        migrations.AddField(
            model_name='burnevent',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_events', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_stats', to='nft_data.nftcollection'),
        ),
        migrations.AddIndex(
            model_name='failedtransaction',
            index=models.Index(fields=['collection_address', 'retry_count', 'last_retry'], name='indexer_fai_collect_06dc16_idx'),
        ),
        migrations.AddField(
            model_name='nftevent',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='nftevent',
            name='nft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nft_data.nft'),
        ),
        migrations.AddField(
            model_name='nftevent',
            name='trait_values',
            field=models.ManyToManyField(related_name='nft_events', to='nft_data.traitvalue'),
        ),
        migrations.AddIndex(
            model_name='platformfee',
            index=models.Index(fields=['event_type', 'timestamp'], name='indexer_pla_event_t_253cfe_idx'),
        ),
        migrations.AddField(
            model_name='traitevent',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_events', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='traitevent',
            name='nft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait_events', to='nft_data.nft'),
        ),
        migrations.AddField(
            model_name='traitevent',
            name='trait_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_events', to='nft_data.traittype'),
        ),
        migrations.AddField(
            model_name='traitevent',
            name='trait_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_events', to='nft_data.traitvalue'),
        ),
        migrations.AddField(
            model_name='traitperformancescore',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_performance_scores', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='traitperformancescore',
            name='trait_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='nft_data.traittype'),
        ),
        migrations.AddField(
            model_name='traitperformancescore',
            name='trait_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='nft_data.traitvalue'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['collection', 'status'], name='indexer_auc_collect_3722d0_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['mint_address', 'start_time'], name='indexer_auc_mint_ad_711e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['status', 'end_time'], name='indexer_auc_status_bd28ff_idx'),
        ),
        migrations.AddIndex(
            model_name='burnevent',
            index=models.Index(fields=['collection', 'timestamp'], name='indexer_bur_collect_5656a6_idx'),
        ),
        migrations.AddIndex(
            model_name='burnevent',
            index=models.Index(fields=['mint_address'], name='indexer_bur_mint_ad_1c834f_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['collection', 'source', 'timestamp'], name='indexer_col_collect_18924d_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['collection_address', 'timestamp'], name='indexer_col_collect_dc6ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['source', 'timestamp'], name='indexer_col_source_7493d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nftevent',
            index=models.Index(fields=['collection_address', 'event_type', 'timestamp'], name='indexer_nft_collect_004828_idx'),
        ),
        migrations.AddIndex(
            model_name='nftevent',
            index=models.Index(fields=['marketplace'], name='indexer_nft_marketp_fd6403_idx'),
        ),
        migrations.AddIndex(
            model_name='nftevent',
            index=models.Index(fields=['mint_address', 'timestamp'], name='indexer_nft_mint_ad_9b3e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='nftevent',
            index=models.Index(fields=['event_type', 'status'], name='indexer_nft_event_t_265375_idx'),
        ),
        migrations.AddIndex(
            model_name='traitevent',
            index=models.Index(fields=['collection', 'trait_type', 'trait_value'], name='indexer_tra_collect_9f0c04_idx'),
        ),
        migrations.AddIndex(
            model_name='traitevent',
            index=models.Index(fields=['mint_address', 'timestamp'], name='indexer_tra_mint_ad_8cd7da_idx'),
        ),
        migrations.AddIndex(
            model_name='traitperformancescore',
            index=models.Index(fields=['collection', 'trait_type', 'trait_value'], name='indexer_tra_collect_f53a37_idx'),
        ),
        migrations.AddIndex(
            model_name='traitperformancescore',
            index=models.Index(fields=['created_at'], name='indexer_tra_created_4aa6da_idx'),
        ),
        migrations.AddIndex(
            model_name='traitperformancescore',
            index=models.Index(fields=['collection', 'performance_score'], name='indexer_tra_collect_be31fd_idx'),
        ),
        migrations.AddIndex(
            model_name='traitperformancescore',
            index=models.Index(fields=['trait_value', 'performance_score'], name='indexer_tra_trait_v_70baf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traitperformancescore',
            unique_together={('collection', 'trait_type', 'trait_value', 'created_at')},
        ),
    ]
