# Generated by Django 5.0.7 on 2025-06-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_initial'),
        ('nft_data', '0002_nft_is_listed_nft_listing_marketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTListing',
            fields=[
                ('listing_id', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('marketplace', models.CharField(max_length=50)),
                ('marketplace_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=9, max_digits=20)),
                ('listing_type', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price'), ('AUCTION', 'Auction'), ('DUTCH_AUCTION', 'Dutch Auction')], default='FIXED_PRICE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('seller_address', models.CharField(max_length=44)),
                ('seller_verified', models.BooleanField(default=False)),
                ('listed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifecycle_stage', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', help_text='Current stage in listing lifecycle', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexer_nft_listings', to='nft_data.nftcollection')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexer_listings', to='nft_data.nft')),
                ('related_nft_event', models.ForeignKey(blank=True, help_text='NFTEvent created when this listing was sold/cancelled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_from_listing', to='indexer.nftevent')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='nftevent',
            name='source_listing',
            field=models.ForeignKey(blank=True, help_text='Original listing that led to this event (for sales/cancellations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_events', to='indexer.nftlisting'),
        ),
        migrations.AddIndex(
            model_name='nftevent',
            index=models.Index(fields=['source_listing', 'event_type'], name='indexer_nft_source__b37f05_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['collection', 'status', 'price'], name='indexer_nft_collect_57e7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['nft', 'status'], name='indexer_nft_nft_id_872f37_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['marketplace', 'status', 'listed_at'], name='indexer_nft_marketp_ca5af9_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['price', 'status'], name='indexer_nft_price_1d2ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['seller_address', 'status'], name='indexer_nft_seller__08f2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['lifecycle_stage', 'status'], name='indexer_nft_lifecyc_e0aa09_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['related_nft_event'], name='indexer_nft_related_da640f_idx'),
        ),
        migrations.AddIndex(
            model_name='nftlisting',
            index=models.Index(fields=['collection', 'lifecycle_stage', 'price'], name='indexer_nft_collect_130d2d_idx'),
        ),
    ]
