# Generated by Django 5.0.7 on 2025-06-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_nftlisting_nftevent_source_listing_and_more'),
        ('nft_data', '0002_nft_is_listed_nft_listing_marketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('magic_eden', 'Magic Eden'), ('tensor', 'Tensor'), ('opensea', 'OpenSea'), ('solanart', 'Solanart'), ('hyperspace', 'Hyperspace')], max_length=50)),
                ('identifier_type', models.CharField(choices=[('symbol', 'Symbol'), ('uuid', 'UUID'), ('slug', 'Slug'), ('collection_id', 'Collection ID')], max_length=20)),
                ('identifier_value', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_ids', to='nft_data.nftcollection')),
            ],
            options={
                'indexes': [models.Index(fields=['marketplace', 'identifier_value'], name='indexer_mar_marketp_dc88fd_idx'), models.Index(fields=['collection', 'marketplace'], name='indexer_mar_collect_c84f25_idx')],
                'unique_together': {('collection', 'marketplace')},
            },
        ),
    ]
