# Generated by Django 5.0.7 on 2025-06-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_marketplaceidentifier'),
        ('nft_data', '0002_nft_is_listed_nft_listing_marketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('event_driven', 'Event Driven')], default='daily', max_length=20)),
                ('floor_price', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('listed_count', models.IntegerField(default=0)),
                ('bid_count', models.IntegerField(default=0)),
                ('market_efficiency_score', models.FloatField(default=0.0)),
                ('holder_confidence_index', models.FloatField(default=0.0)),
                ('liquidity_health_score', models.FloatField(default=0.0)),
                ('market_condition', models.CharField(choices=[('bull', 'Bull Market'), ('bear', 'Bear Market'), ('sideways', 'Sideways'), ('volatile', 'Volatile')], default='sideways', max_length=20)),
                ('trigger_events', models.JSONField(default=list, help_text='Events that triggered this snapshot (for event_driven type)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('query_parameters', models.JSONField(default=dict, help_text='Parameters used in the analytics query')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionTrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentum_score', models.FloatField(default=0.0, help_text='Overall momentum: combines price, volume, and activity trends')),
                ('trend_direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral'), ('volatile', 'Volatile')], default='neutral', max_length=20)),
                ('price_momentum_24h', models.FloatField(default=0.0)),
                ('price_momentum_7d', models.FloatField(default=0.0)),
                ('volume_momentum_24h', models.FloatField(default=0.0)),
                ('volume_momentum_7d', models.FloatField(default=0.0)),
                ('activity_momentum', models.FloatField(default=0.0, help_text='Based on sales frequency and bid activity')),
                ('support_level', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('resistance_level', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('volatility_index', models.FloatField(default=0.0, help_text='Price volatility measure (0 = stable, 1 = highly volatile)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossMarketplaceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensor_floor', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('magic_eden_floor', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('price_differential', models.DecimalField(decimal_places=4, default=0, help_text='Percentage difference between marketplace floors', max_digits=10)),
                ('tensor_volume_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('magic_eden_volume_24h', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('volume_distribution', models.FloatField(default=0.0, help_text='Volume distribution ratio (0 = all ME, 1 = all Tensor)')),
                ('tensor_listings', models.IntegerField(default=0)),
                ('magic_eden_listings', models.IntegerField(default=0)),
                ('liquidity_preference', models.FloatField(default=0.0, help_text='Where liquidity is concentrated (0 = ME, 1 = Tensor)')),
                ('arbitrage_opportunity', models.DecimalField(decimal_places=4, default=0, help_text='Potential arbitrage profit percentage', max_digits=10)),
                ('arbitrage_direction', models.CharField(choices=[('tensor_to_me', 'Buy Tensor, Sell Magic Eden'), ('me_to_tensor', 'Buy Magic Eden, Sell Tensor'), ('none', 'No Arbitrage')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_spike', 'Price Spike'), ('price_drop', 'Price Drop'), ('volume_surge', 'Volume Surge'), ('supply_pressure', 'Supply Pressure'), ('bid_activity', 'High Bid Activity'), ('arbitrage', 'Arbitrage Opportunity'), ('trend_reversal', 'Trend Reversal')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('trigger_value', models.DecimalField(blank=True, decimal_places=9, help_text='The value that triggered this alert (price, percentage, etc.)', max_digits=20, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=9, help_text='The threshold that was crossed', max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('dismissed_by', models.JSONField(default=list, help_text='List of user IDs who dismissed this alert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Overall sentiment: -1 (very bearish) to +1 (very bullish)')),
                ('supply_pressure', models.FloatField(default=0.0, help_text='Selling pressure based on listing increases')),
                ('demand_strength', models.FloatField(default=0.0, help_text='Buying demand based on bid activity and sales velocity')),
                ('market_depth_score', models.FloatField(default=0.0, help_text='Liquidity depth based on bid/listing distribution')),
                ('fomo_indicator', models.FloatField(default=0.0, help_text='Fear of missing out indicator based on rapid price/volume changes')),
                ('fud_indicator', models.FloatField(default=0.0, help_text='Fear, uncertainty, doubt indicator based on sell pressure')),
                ('trigger_events', models.JSONField(default=list, help_text='List of events that triggered this sentiment analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='bid_count',
            field=models.IntegerField(default=0, help_text='Current number of active bids (from Tensor numBids)'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='calculation_method',
            field=models.JSONField(default=dict, help_text='Methodology used for each field in aggregated records'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='floor_price_net_fees',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Floor price after marketplace fees (from Tensor buyNowPriceNetFees)', max_digits=20),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='highest_bid',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Highest current bid in SOL (from Tensor sellNowPrice)', max_digits=20),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='holder_confidence_index',
            field=models.FloatField(default=0.0, help_text='Confidence based on listing % trends and bid/listing ratio'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='liquidity_health_score',
            field=models.FloatField(default=0.0, help_text='Health score based on bids vs listings balance'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='listing_change_24h',
            field=models.DecimalField(decimal_places=4, default=0, help_text='24h change in listings percentage (from Tensor numListed24h)', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='listing_change_7d',
            field=models.DecimalField(decimal_places=4, default=0, help_text='7d change in listings percentage (from Tensor numListed7d)', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='market_cap',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Collection market cap in lamports (from Tensor marketCap)', max_digits=25),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='market_efficiency_score',
            field=models.FloatField(default=0.0, help_text='Bid-ask spread efficiency: (floor_price - highest_bid) / floor_price'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='percent_listed',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Percentage of collection listed (from Tensor pctListed)', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='price_change_7d',
            field=models.DecimalField(decimal_places=4, default=0, help_text='7d floor price change percentage (from Tensor floor7d)', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Complete API response from marketplace for advanced analytics'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='sales_count_24h',
            field=models.IntegerField(default=0, help_text='Number of sales in last 24h (from Tensor sales24h)'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='sales_count_7d',
            field=models.IntegerField(default=0, help_text='Number of sales in last 7d (from Tensor sales7d)'),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='sales_count_all',
            field=models.IntegerField(default=0, help_text='Total sales count (from Tensor salesAll)'),
        ),
        migrations.AlterField(
            model_name='collectionmarketstats',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=4, default=0, help_text='24h floor price change percentage (from Tensor floor24h)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['collection', 'price_change_24h'], name='indexer_col_collect_c45507_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['collection', 'percent_listed'], name='indexer_col_collect_d3e697_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['collection', 'market_efficiency_score'], name='indexer_col_collect_c652fa_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['price_change_24h', 'timestamp'], name='indexer_col_price_c_cb0b30_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['percent_listed', 'timestamp'], name='indexer_col_percent_d7e7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceidentifier',
            index=models.Index(fields=['is_verified', 'last_verified'], name='indexer_mar_is_veri_0260d5_idx'),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='analyticsusage',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_usage', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='collectiontrendanalysis',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analysis', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='crossmarketplacecomparison',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_comparisons', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='marketalert',
            name='associated_stats',
            field=models.ForeignKey(blank=True, help_text='The stats record that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexer.collectionmarketstats'),
        ),
        migrations.AddField(
            model_name='marketalert',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_alerts', to='nft_data.nftcollection'),
        ),
        migrations.AddField(
            model_name='marketsentimentsnapshot',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_snapshots', to='nft_data.nftcollection'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['collection', 'snapshot_type', 'created_at'], name='indexer_ana_collect_c92c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['created_at'], name='indexer_ana_created_f2aa00_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['market_condition', 'created_at'], name='indexer_ana_market__2d90cb_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsusage',
            index=models.Index(fields=['feature_name', 'accessed_at'], name='indexer_ana_feature_fafcee_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsusage',
            index=models.Index(fields=['collection', 'feature_name'], name='indexer_ana_collect_8ccba3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsusage',
            index=models.Index(fields=['accessed_at'], name='indexer_ana_accesse_6efac6_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontrendanalysis',
            index=models.Index(fields=['collection', 'created_at'], name='indexer_col_collect_7a3818_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontrendanalysis',
            index=models.Index(fields=['momentum_score', 'created_at'], name='indexer_col_momentu_1ba49c_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontrendanalysis',
            index=models.Index(fields=['trend_direction', 'created_at'], name='indexer_col_trend_d_93c321_idx'),
        ),
        migrations.AddIndex(
            model_name='crossmarketplacecomparison',
            index=models.Index(fields=['collection', 'created_at'], name='indexer_cro_collect_b110bc_idx'),
        ),
        migrations.AddIndex(
            model_name='crossmarketplacecomparison',
            index=models.Index(fields=['arbitrage_opportunity', 'created_at'], name='indexer_cro_arbitra_8d80ec_idx'),
        ),
        migrations.AddIndex(
            model_name='marketalert',
            index=models.Index(fields=['collection', 'alert_type', 'created_at'], name='indexer_mar_collect_96b226_idx'),
        ),
        migrations.AddIndex(
            model_name='marketalert',
            index=models.Index(fields=['severity', 'is_active', 'created_at'], name='indexer_mar_severit_906a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketalert',
            index=models.Index(fields=['is_active', 'is_resolved'], name='indexer_mar_is_acti_6e785c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsentimentsnapshot',
            index=models.Index(fields=['collection', 'created_at'], name='indexer_mar_collect_443332_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsentimentsnapshot',
            index=models.Index(fields=['sentiment_score', 'created_at'], name='indexer_mar_sentime_f02a05_idx'),
        ),
    ]
