# Generated by Django 5.0.7 on 2025-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0007_nftlisting_bid_count_nftlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmarketstats',
            name='source',
            field=models.CharField(choices=[('magic_eden', 'Magic Eden'), ('tensor', 'Tensor'), ('blockchain', 'Blockchain'), ('traitkeeper', 'TraitKeeper'), ('aggregated', 'Aggregated')], default='aggregated', max_length=20),
        ),
    ]
