# Generated by Django 5.0.7 on 2025-07-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0008_alter_collectionmarketstats_source'),
        ('nft_data', '0007_nftcollection_api_quota_limit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advancedtraitanalytics',
            unique_together={('trait_type', 'trait_value', 'collection')},
        ),
    ]
