# Generated by Django 5.0.7 on 2025-08-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0009_alter_advancedtraitanalytics_unique_together'),
        ('nft_data', '0007_nftcollection_api_quota_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftevent',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='nftevent',
            name='nft',
        ),
        migrations.AlterField(
            model_name='nftevent',
            name='collection_address',
            field=models.ForeignKey(db_column='collection_address', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nft_data.nftcollection'),
        ),
        migrations.AlterField(
            model_name='nftevent',
            name='mint_address',
            field=models.ForeignKey(db_column='mint_address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nft_data.nft'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionmarketstats',
            unique_together={('collection', 'source')},
        ),
    ]
