# Generated by Django 5.0.7 on 2025-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0010_remove_nftevent_collection_remove_nftevent_nft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftevent',
            name='buyer',
            field=models.CharField(blank=True, db_index=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='nftevent',
            name='seller',
            field=models.CharField(blank=True, db_index=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='traitperformancescore',
            name='performance_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
