# Generated by Django 5.0.7 on 2025-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0011_alter_nftevent_buyer_alter_nftevent_seller_and_more'),
        ('nft_data', '0009_nft_vitality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmarketstats',
            name='holder_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='vitality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='collectionmarketstats',
            name='floor_price_net_fees',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Floor price after marketplace fees ', max_digits=20),
        ),
        migrations.AlterField(
            model_name='collectionmarketstats',
            name='highest_bid',
            field=models.DecimalField(decimal_places=9, default=0, help_text='Highest current bid in SOL ', max_digits=20),
        ),
        migrations.AlterField(
            model_name='collectionmarketstats',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=4, default=0, help_text='24h floor price change percentage )', max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectionmarketstats',
            name='price_change_7d',
            field=models.DecimalField(decimal_places=4, default=0, help_text='7d floor price change percentage ', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='collectionmarketstats',
            index=models.Index(fields=['vitality_score'], name='indexer_col_vitalit_e60b20_idx'),
        ),
    ]
