# Generated by Django 5.0.7 on 2025-10-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0013_remove_advancedcrossmarketplaceanalysis_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmarketstats',
            name='owners_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionmarketstats',
            name='sales_count_24h',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
