# Generated by Django 5.0.7 on 2025-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0014_collectionmarketstats_owners_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownDiscriminator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(db_index=True, max_length=44)),
                ('discriminator', models.CharField(db_index=True, max_length=16)),
                ('inferred_marketplace', models.CharField(blank=True, max_length=50)),
                ('inferred_action', models.CharField(blank=True, max_length=50)),
                ('has_nft_transfer', models.BooleanField(default=False)),
                ('has_native_transfer', models.BooleanField(default=False)),
                ('log_patterns', models.JSONField(default=list)),
                ('sample_signatures', models.JSONField(default=list)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('should_ignore', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['program_id', 'is_approved'], name='indexer_unk_program_67db51_idx'), models.Index(fields=['inferred_marketplace', 'inferred_action'], name='indexer_unk_inferre_b6f367_idx')],
                'unique_together': {('program_id', 'discriminator')},
            },
        ),
    ]
