# Generated by Django 5.0.7 on 2025-05-27 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('transaction', 'Transaction'), ('sweep', 'Collection Sweep'), ('trait_performance', 'Trait Performance Change'), ('high_profile_transfer', 'High Profile Transfer'), ('wallet_activity', 'Wallet Activity'), ('collection_approval', 'Collection Approval')], max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('transaction', 'Transactions'), ('sweep', 'Collection Sweeps'), ('trait_performance', 'Trait Performance Changes'), ('high_profile_transfer', 'High Profile Transfers'), ('wallet_activity', 'Wallet Activity'), ('collection_approval', 'Collection Approvals')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('notify_via_email', models.BooleanField(default=False)),
                ('notify_via_push', models.BooleanField(default=False)),
                ('transaction_min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum transaction value for notification (SOL)', max_digits=20, null=True)),
                ('specific_collections', models.JSONField(blank=True, default=list, help_text='List of collection IDs to notify about')),
                ('specific_traits', models.JSONField(blank=True, default=list, help_text='List of trait type IDs to notify about')),
                ('specific_wallets', models.JSONField(blank=True, default=list, help_text='List of wallet addresses to notify about')),
            ],
        ),
    ]
