# Generated by Django 5.0.7 on 2025-09-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_delete_adminnotification'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('server_load', 'High Server Load'), ('failed_login', 'Failed Login Attempt'), ('collection_populated', 'Collections Populated'), ('collection_refreshed', 'Collections Refreshed'), ('collection_submitted', 'Collection Submitted'), ('collection_action', 'Collection Action'), ('system_alert', 'System Alert'), ('magic_eden_issue', 'Magic Eden Issue'), ('data_anomaly', 'Data Anomaly'), ('performance_issue', 'Performance Issue'), ('collection_issue', 'Collection Issue')], max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
