# Generated by Django 5.0.7 on 2025-10-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_bid_nftlisting'),
        ('nft_data', '0013_nft_active_auction_nft_asking_price_and_more'),
        ('notifications', '0003_adminnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.bid'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.nftlisting'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='nft_data.nft'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('sweep', 'Collection Sweep'), ('trait_performance', 'Trait Performance Change'), ('high_profile_transfer', 'High Profile Transfer'), ('wallet_activity', 'Wallet Activity'), ('nft_listed', 'NFT Listed'), ('nft_sold', 'NFT Sold'), ('nft_delisted', 'NFT Delisted'), ('bid_received', 'Bid Received'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_outbid', 'Outbid on NFT'), ('watchlist_listed', 'Watchlist Item Listed'), ('watchlist_price_change', 'Watchlist Price Change'), ('achievement_earned', 'Achievement Earned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('transaction', 'Transactions'), ('sweep', 'Collection Sweeps'), ('trait_performance', 'Trait Performance Changes'), ('high_profile_transfer', 'High Profile Transfers'), ('wallet_activity', 'Wallet Activity'), ('nft_listed', 'NFT Listings'), ('nft_sold', 'NFT Sales'), ('bid_received', 'Bids Received'), ('bid_accepted', 'Bids Accepted'), ('bid_outbid', 'Outbid Alerts'), ('watchlist_alerts', 'Watchlist Alerts'), ('achievement_earned', 'Achievement Notifications')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'event_type'], name='notificatio_user_id_b16834_idx'),
        ),
    ]
